USE [NORCELEC]
GO

/****** Object:  Table [dbo].[FACTURA]    Script Date: 05/12/2025 05:45:04 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTURA](
	[Empresa] [bigint] NOT NULL,
	[No_Factura] [bigint] NOT NULL,
	[Partida] [bigint] NOT NULL,
	[UUID] [nvarchar](100) NULL,
	[FechaHoraFactura] [datetime] NULL,
	[Estatus] [nvarchar](50) NULL,
	[Cve_Cliente] [bigint] NULL,
	[Cliente_Nombre] [nvarchar](255) NULL,
	[ClienteRFC] [nvarchar](15) NULL,
	[ClienteCalle] [nvarchar](255) NULL,
	[ClienteNoExterior] [nvarchar](20) NULL,
	[ClienteNoInterior] [nvarchar](50) NULL,
	[ClienteColonia] [nvarchar](100) NULL,
	[ClienteMunicipio] [nvarchar](100) NULL,
	[ClienteCP] [nvarchar](5) NULL,
	[ClienteCiudad] [nvarchar](100) NULL,
	[ClienteEstado] [nvarchar](100) NULL,
	[ClienteTelefono] [nvarchar](100) NULL,
	[ClienteFax] [nvarchar](100) NULL,
	[ClienteEmail] [nvarchar](255) NULL,
	[ClienteContacto] [nvarchar](50) NULL,
	[ClienteTelContacto] [nvarchar](100) NULL,
	[RegimenFiscalReceptor] [nvarchar](255) NULL,
	[MetodoPago] [nvarchar](255) NULL,
	[FormaPago] [nvarchar](255) NULL,
	[CuentaPago] [nvarchar](255) NULL,
	[BancoPago] [nvarchar](255) NULL,
	[UsoCFDI] [nvarchar](255) NULL,
	[CveProdServ] [nvarchar](50) NULL,
	[CveUnidadMedida] [nvarchar](10) NULL,
	[UnidadMedida] [nvarchar](255) NULL,
	[Cve_PedCliente] [nvarchar](100) NULL,
	[Cve_Proveedor] [nvarchar](100) NULL,
	[Orden_Surtimiento] [nvarchar](100) NULL,
	[Contrato_Cliente] [nvarchar](100) NULL,
	[No_Pedido] [bigint] NULL,
	[Num_Folio] [bigint] NULL,
	[LugarDeEntrega] [bigint] NULL,
	[NombreLugarDeEntrega] [nvarchar](150) NULL,
	[LugarDeEntregaCalle] [nvarchar](80) NULL,
	[LugarDeEntregaNoExterior] [nvarchar](20) NULL,
	[LugarDeEntregaNoInterior] [nvarchar](50) NULL,
	[LugarDeEntregaColonia] [nvarchar](50) NULL,
	[LugarDeEntregaMunicipio] [nvarchar](50) NULL,
	[LugarDeEntregaCP] [nvarchar](5) NULL,
	[LugarDeEntregaCiudad] [nvarchar](50) NULL,
	[LugarDeEntregaEstado] [nvarchar](50) NULL,
	[LugarDeEntregaTelefono] [nvarchar](50) NULL,
	[LugarDeEntregaFax] [nvarchar](50) NULL,
	[LugarDeEntregaEmail] [nvarchar](255) NULL,
	[LugarDeEntregaContacto] [nvarchar](50) NULL,
	[LugarDeEntregaTelContacto] [nvarchar](50) NULL,
	[LugarDeEntregaAtencion] [nvarchar](50) NULL,
	[LugarDeEntregaTelAtencion] [nvarchar](50) NULL,
	[CondicionesPago] [nvarchar](100) NULL,
	[PorcentajeIVA] [numeric](18, 2) NULL,
	[CveArticuloCliente] [nvarchar](50) NULL,
	[Cantidad] [numeric](18, 0) NULL,
	[Descripcion] [nvarchar](1000) NULL,
	[ComentariosPartida] [nvarchar](max) NULL,
	[Precio] [numeric](18, 4) NULL,
	[PartidaSubtotal] [numeric](18, 4) NULL,
	[PartidaDescuento] [numeric](18, 4) NULL,
	[PartidaIVA] [numeric](18, 4) NULL,
	[PartidaTotal] [numeric](18, 4) NULL,
	[FacturaSubtotal] [numeric](18, 4) NULL,
	[FacturaDescuento] [numeric](18, 4) NULL,
	[FacturaIVA] [numeric](18, 4) NULL,
	[FacturaTotal] [numeric](18, 4) NULL,
	[ImporteEnLetra] [nvarchar](255) NULL,
	[Layout] [bit] NULL,
	[USUARIOLAYOUT] [bigint] NULL,
	[FECHAHORALAYOUT] [datetime] NULL,
	[COMPUTADORALAYOUT] [nvarchar](50) NULL,
	[USUARIO] [bigint] NULL,
	[FECHAHORA] [datetime] NULL,
	[COMPUTADORA] [nvarchar](50) NULL,
	[USUARIOCANCELO] [bigint] NULL,
	[FECHAHORACANCELO] [datetime] NULL,
	[COMPUTADORACANCELO] [nvarchar](50) NULL,
 CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED 
(
	[Empresa] ASC,
	[No_Factura] ASC,
	[Partida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

