USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[OP_ACUSE_TELA_GUARDAR]    Script Date: 27/03/2026 01:35:14 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[OP_ACUSE_TELA_GUARDAR]
	@EMPRESA BIGINT,
	@NO_OP BIGINT,
	@TIPOMATERIAL NVARCHAR(1),
	@CVE_MATERIAL NVARCHAR(10),
	@DESCRIPCIONMATERIAL NVARCHAR(255),
	@FOLIO BIGINT,
	@CANTIDAD NUMERIC(18,2),
	@FECHAFIRMAACUSE DATE,
	@QUIENFIRMAACUSE NVARCHAR(255),
	@OBSERVACIONES NVARCHAR(MAX),
	@TIPOARCHIVO NVARCHAR(10),
	@USUARIO BIGINT,
	@COMPUTADORA NVARCHAR(50)
AS
BEGIN

	DECLARE @CONSECUTIVO INT
	DECLARE @RUTAACUSE NVARCHAR(255)
	SET @RUTAACUSE = '\\192.168.1.9\DAC ORCELEC\AcusesRemisiones\'
	DECLARE @SECIERRA AS BIT

	SELECT @CONSECUTIVO = ISNULL(MAX(Consecutivo),0)+1 FROM OP_ACUSES_TELA WHERE Empresa = @EMPRESA AND No_OP = @NO_OP AND TipoMaterial = @TIPOMATERIAL AND Cve_Material = @CVE_MATERIAL

	INSERT INTO [dbo].[OP_ACUSES_TELA]
    (
		[Empresa]
        ,[No_OP]
        ,[Consecutivo]
        ,[TipoMaterial]
        ,[Cve_Material]
        ,[DescripcionMaterial]
        ,[Folio]
        ,[Cantidad]
        ,[FechaFirmaAcuse]
        ,[QuienFirmaAcuse]
        ,[Observaciones]
        ,[RutaAcuse]
        ,[USUARIO]
        ,[FECHAHORA]
        ,[COMPUTADORA]
	)
	SELECT
		@EMPRESA,
		@NO_OP,
		@CONSECUTIVO,
		@TIPOMATERIAL,
		@CVE_MATERIAL,
		@DESCRIPCIONMATERIAL,
		@FOLIO,
		@CANTIDAD,
		@FECHAFIRMAACUSE,
		@QUIENFIRMAACUSE,
		@OBSERVACIONES,
		@RUTAACUSE + CONVERT(NVARCHAR,@NO_OP) + @TIPOMATERIAL + @CVE_MATERIAL + CONVERT(NVARCHAR,@CONSECUTIVO) + '.' + @TIPOARCHIVO,
		@USUARIO,
		GETDATE(),
		@COMPUTADORA

	DECLARE 
		@CONSUMO_TOTAL NUMERIC(18,2),
		@TOTAL_ENVIADO NUMERIC(18,2)

	SELECT @CONSUMO_TOTAL = (
		SELECT ISNULL(OPEM.Cantidad,0) 
		FROM OP_EXPLOSION_MATERIALES OPEM 
		WHERE OPEM.Empresa = @EMPRESA AND OPEM.No_OP = @NO_OP 
		AND OPEM.TipoMaterial = @TIPOMATERIAL AND OPEM.Cve_Material = @CVE_MATERIAL)+
		(
		SELECT ISNULL(SUM(OPEMI.Cantidad),0) 
		FROM OP_EXPLOSION_MATERIALES_INSPECTOR OPEMI 
		WHERE OPEMI.Empresa = @EMPRESA AND OPEMI.No_OP = @No_OP 
		AND OPEMI.TipoMaterial = @TIPOMATERIAL AND OPEMI.Cve_Material = @CVE_MATERIAL 
		AND OPEMI.TipoMovimiento = 'FALTANTE')

	SELECT @TOTAL_ENVIADO = SUM(Cantidad) 
	FROM OP_ACUSES_TELA 
	WHERE Empresa = @EMPRESA AND No_OP = @NO_OP AND TipoMaterial = @TIPOMATERIAL 
	AND Cve_Material = @CVE_MATERIAL

	IF @TOTAL_ENVIADO >= @CONSUMO_TOTAL
	BEGIN --CIERRA EL PENDIENTE DE ENVIO DE MATERIAL
		UPDATE
			OP_EXPLOSION_MATERIALES
		SET
			RecibidoCompletoPorMaquilador = 1,
			USUARIORECIBIDOCOMPLETO = @USUARIO,
			FECHAHORARECIBIDOCOMPLETO = GETDATE(),
			COMPUTADORARECIBIDOCOMPLETO = @COMPUTADORA
		WHERE
			Empresa = @EMPRESA
		AND No_OP = @NO_OP
		AND TipoMaterial = @TIPOMATERIAL
		AND Cve_Material = @CVE_MATERIAL

		SET @SECIERRA = 1
	END
	ELSE
	BEGIN
		SET @SECIERRA = 0
	END

	SELECT
			@CONSECUTIVO AS Consecutivo,
			@SECIERRA AS SeCierra
END
GO

