USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[OP_AUTORIZAR_REGRESA_ASIGNACION]    Script Date: 03/10/2025 06:25:56 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[OP_AUTORIZAR_REGRESA_ASIGNACION]
	@EMPRESA BIGINT,
	@NO_OP BIGINT,
	@ESTATUS NVARCHAR(50),
	@CVE_MAQUILADOR BIGINT,
	@OBSERVACIONES NVARCHAR(MAX),
	@USUARIO BIGINT,
	@COMPUTADORA NVARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @NOM_MAQUILADORASIGNADO NVARCHAR(255)
	DECLARE @CVE_MAQUILADORORIGINAL BIGINT
	DECLARE @NOM_MAQUILADORORIGINAL NVARCHAR(255)
	DECLARE @CONSECUTIVO BIGINT
	DECLARE @OMITIRINVENTARIO BIT
	DECLARE @CONSECUTIVOINV BIGINT

    -- Insert statements for procedure here
	IF @ESTATUS = 'AUTORIZADA'
	BEGIN

		SELECT @NOM_MAQUILADORASIGNADO = Encargado FROM MAQUILADOR WHERE Cve_Maquilador = @CVE_MAQUILADOR
		SELECT @CVE_MAQUILADORORIGINAL = Cve_Maquilador, @NOM_MAQUILADORORIGINAL = Nom_Maquilador FROM OP_ASIGNACION WHERE Empresa = @EMPRESA AND No_OP = @NO_OP

		IF @CVE_MAQUILADORORIGINAL <> @CVE_MAQUILADOR
		BEGIN--ACTUALIZA MAQUILADOR YA QUE SE SELECCIONO UNO DIFERENTE
			UPDATE
				OP_ASIGNACION
			SET 
				Cve_Maquilador = @CVE_MAQUILADOR,
				Nom_Maquilador = @NOM_MAQUILADORASIGNADO,
				Estatus = @ESTATUS,
				USUARIOAutorizo = @USUARIO,
				FECHAHORAAutorizo = GETDATE(),
				COMPUTADORAAutorizo = @COMPUTADORA
			WHERE
				Empresa = @EMPRESA
			AND No_OP = @NO_OP

			--OBTIENE EL ULTIMO CONSECUTIVO DE LAS OBSERVACIONES DEL PROCESO DE AUTORIZACIÓN
			SELECT @CONSECUTIVO = ISNULL(MAX(Consecutivo),0) FROM OP_OBSERVACIONESAUTORIZAR WHERE Empresa = @EMPRESA AND No_OP = @NO_OP

			--AUMENTE EN 1 EL CONSECUTIVO
			SET @CONSECUTIVO +=1

			--INSERTA EL REGISTRO EN OP_OBSERVACIONESAUTORIZAR
			INSERT INTO OP_OBSERVACIONESAUTORIZAR
			(
				Empresa,
				NO_OP,
				Consecutivo,
				TipoAutorizacion,
				Observaciones,
				Cve_MaquiladorOriginal,
				Nom_MaquiladorOriginal,
				Cve_MaquiladorAsignado,
				Nom_MaquiladorAsignado,
				USUARIO,
				FECHAHORA,
				COMPUTADORA
			)
			SELECT
				@EMPRESA,
				@NO_OP,
				@CONSECUTIVO,
				'AUTORIZADA',
				@OBSERVACIONES,
				@CVE_MAQUILADORORIGINAL,
				@NOM_MAQUILADORORIGINAL,
				@CVE_MAQUILADOR,
				@NOM_MAQUILADORASIGNADO,
				@USUARIO,
				GETDATE(),
				@COMPUTADORA
		END
		ELSE
		BEGIN
			UPDATE
				OP_ASIGNACION
			SET 
				Estatus = @ESTATUS,
				USUARIOAutorizo = @USUARIO,
				FECHAHORAAutorizo = GETDATE(),
				COMPUTADORAAutorizo = @COMPUTADORA
			WHERE
				Empresa = @EMPRESA
			AND No_OP = @NO_OP

			--OBTIENE EL ULTIMO CONSECUTIVO DE LAS OBSERVACIONES DEL PROCESO DE AUTORIZACIÓN
			SELECT @CONSECUTIVO = ISNULL(MAX(Consecutivo),0) FROM OP_OBSERVACIONESAUTORIZAR WHERE Empresa = @EMPRESA AND No_OP = @NO_OP

			--AUMENTE EN 1 EL CONSECUTIVO
			SET @CONSECUTIVO +=1

			--INSERTA EL REGISTRO EN OP_OBSERVACIONESAUTORIZAR
			INSERT INTO OP_OBSERVACIONESAUTORIZAR
			(
				Empresa,
				NO_OP,
				Consecutivo,
				TipoAutorizacion,
				Observaciones,
				Cve_MaquiladorOriginal,
				Nom_MaquiladorOriginal,
				Cve_MaquiladorAsignado,
				Nom_MaquiladorAsignado,
				USUARIO,
				FECHAHORA,
				COMPUTADORA
			)
			VALUES
			(
				@EMPRESA,
				@NO_OP,
				@CONSECUTIVO,
				'AUTORIZADA',
				@OBSERVACIONES,
				@CVE_MAQUILADORORIGINAL,
				@NOM_MAQUILADORORIGINAL,
				@CVE_MAQUILADORORIGINAL,
				@NOM_MAQUILADORORIGINAL,
				@USUARIO,
				GETDATE(),
				@COMPUTADORA
			)

		END

		--SELECT @OMITIRINVENTARIO = MAX(CONVERT(TINYINT, ISNULL(PI.OmitirInventario,0)))
  --      FROM PEDIDO_INTERNO PI
  --      INNER JOIN PEDIDO_INTERNO_TALLAS PIT
  --              ON PI.Empresa = PIT.Empresa AND PI.No_Pedido = PIT.No_Pedido
  --      WHERE PIT.Empresa = @EMPRESA AND PIT.No_OP = @NO_OP

  --      IF @OMITIRINVENTARIO = 1
  --      BEGIN
		--	--Actualiza inventario de producto terminado con las cantidades de la OP autorizada
		--	MERGE INTO PRENDA_INVENTARIO AS IPT
		--	USING (
		--			SELECT @EMPRESA AS Empresa, PIT.Cve_Prenda, PIT.Talla, SUM(PIT.Cantidad) AS Cantidad
		--			FROM PEDIDO_INTERNO_TALLAS PIT
		--			WHERE PIT.Empresa = @EMPRESA AND PIT.No_OP = @NO_OP
		--			GROUP BY PIT.Cve_Prenda, PIT.Talla
		--	) AS SRC
		--	ON IPT.Empresa = SRC.Empresa AND IPT.Cve_Prenda = SRC.Cve_Prenda AND IPT.Talla = SRC.Talla
		--	WHEN MATCHED THEN
		--			UPDATE SET IPT.Cantidad = IPT.Cantidad + SRC.Cantidad
		--	WHEN NOT MATCHED THEN
		--			INSERT (Empresa, Cve_Prenda, Talla, Cantidad)
		--			VALUES (SRC.Empresa, SRC.Cve_Prenda, SRC.Talla, SRC.Cantidad);

		--	--Registra movimiento en bitácora de inventario
  --          SELECT @CONSECUTIVOINV = ISNULL(MAX(Consecutivo),0)
  --          FROM PRENDA_INVENTARIO_BITACORA
  --          WHERE Empresa = @EMPRESA AND No_OP = @NO_OP;

  --          INSERT INTO PRENDA_INVENTARIO_BITACORA
  --              (Empresa, No_OP, Consecutivo, Cve_Prenda, Talla, Cantidad, USUARIO, FECHAHORA, COMPUTADORA)
  --          SELECT
  --              @EMPRESA AS Empresa,
  --              @NO_OP AS No_OP,
  --              @CONSECUTIVOINV + ROW_NUMBER() OVER (ORDER BY PIT.Cve_Prenda, PIT.Talla) AS Consecutivo,
  --              PIT.Cve_Prenda,
  --              PIT.Talla,
  --              SUM(PIT.Cantidad) AS Cantidad,
  --              @USUARIO,
  --              GETDATE(),
  --              @COMPUTADORA
  --          FROM PEDIDO_INTERNO_TALLAS PIT
  --          WHERE PIT.Empresa = @EMPRESA AND PIT.No_OP = @NO_OP
  --          GROUP BY PIT.Cve_Prenda, PIT.Talla;
  --      END
    END

	IF @ESTATUS = 'REGRESARASIGNACION'
	BEGIN
		
		SELECT @CVE_MAQUILADORORIGINAL = Cve_Maquilador, @NOM_MAQUILADORORIGINAL = Nom_Maquilador FROM OP_ASIGNACION WHERE Empresa = @EMPRESA AND No_OP = @NO_OP
		
		--SOLO ACTUALIZA EL ESTATUS A PENDIENTE DE ASIGNACIÓN
		UPDATE
			OP_ASIGNACION
		SET 
			Asignada = 0,
			FechaFinalizacion = NULL,
			DiasProceso = 0,
			Estatus = 'PENDIENTE',
			Cve_Maquilador = NULL,
			Nom_Maquilador = NULL
		WHERE
			Empresa = @EMPRESA
		AND No_OP = @NO_OP

		--OBTIENE EL ULTIMO CONSECUTIVO DE LAS OBSERVACIONES DEL PROCESO DE AUTORIZACIÓN
		SELECT @CONSECUTIVO = ISNULL(MAX(Consecutivo),0) FROM OP_OBSERVACIONESAUTORIZAR WHERE Empresa = @EMPRESA AND No_OP = @NO_OP

		--AUMENTE EN 1 EL CONSECUTIVO
		SET @CONSECUTIVO +=1

		--INSERTA EL REGISTRO EN OP_OBSERVACIONESAUTORIZAR
		INSERT INTO OP_OBSERVACIONESAUTORIZAR
		(
			Empresa,
			NO_OP,
			Consecutivo,
			TipoAutorizacion,
			Observaciones,
			Cve_MaquiladorOriginal,
			Nom_MaquiladorOriginal,
			USUARIO,
			FECHAHORA,
			COMPUTADORA
		)
		SELECT
			@EMPRESA,
			@NO_OP,
			@CONSECUTIVO,
			'REGRESARASIGNACION',
			@OBSERVACIONES,
			@CVE_MAQUILADORORIGINAL,
			@NOM_MAQUILADORORIGINAL,
			@USUARIO,
			GETDATE(),
			@COMPUTADORA
	END
END
GO

