USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[PEDIDO_INTERNO_AUTORIZAR]    Script Date: 07/08/2025 05:49:58 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PEDIDO_INTERNO_AUTORIZAR]
	-- Add the parameters for the stored procedure here
	@EMPRESA BIGINT,
	@NO_PEDIDO BIGINT,
	@NOTAS_AL_AUTORIZAR NVARCHAR(MAX),
	@USUARIO BIGINT,
	@COMPUTADORA NVARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    DECLARE @TRAN_STARTED BIT
	SET @TRAN_STARTED = 0
	
	BEGIN TRY
	
		BEGIN TRANSACTION
		SET @TRAN_STARTED = 1

	    -- Cambia el estatus de pedido a autorizado
		UPDATE
			PEDIDO_INTERNO
		SET
			Status = 'AUTORIZADO',
			ObservacionesAlAutorizar = @NOTAS_AL_AUTORIZAR,
			USUARIOAUTORIZO = @USUARIO,
			FECHAHORAAUTORIZO = GETDATE(),
			COMPUTADORAAUTORIZO = @COMPUTADORA
		WHERE
			Empresa = @EMPRESA
		AND No_Pedido = @NO_PEDIDO

		DECLARE
			@TIPOPEDIDO AS NVARCHAR(10)

		SELECT @TIPOPEDIDO = FA.TipoPedido FROM PEDIDO_INTERNO PI,FOLIOS_ADMINISTRACION FA WHERE PI.Empresa = @EMPRESA AND PI.No_Pedido = @NO_PEDIDO AND FA.Empresa = PI.Empresa AND FA.Num_Folio = PI.Num_Folio

		IF @TIPOPEDIDO NOT IN ('C','L')
        BEGIN
			--Explosiona pedido
			EXEC SP_EXPLOSION_MATERIALES_SUGERIDO_COMPRA @EMPRESA,@NO_PEDIDO
		END

		COMMIT TRANSACTION
		SET @TRAN_STARTED = 0

	END TRY
	
	BEGIN CATCH
	
		IF @TRAN_STARTED = 1
		BEGIN
			ROLLBACK TRANSACTION
		END
		
		DECLARE @ERROR_MESSAGE NVARCHAR(4000)
		DECLARE @ERROR_SEVERITY INT
		DECLARE @ERROR_STATE INT
		
		SELECT @ERROR_MESSAGE = ERROR_MESSAGE(),
			   @ERROR_SEVERITY = ERROR_SEVERITY(),
			   @ERROR_STATE = ERROR_STATE()
			   
		RAISERROR(@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE)

	END CATCH
END
GO

