USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[RPT_PEDIDO_INTERNO_PARTIDAS]    Script Date: 05/09/2025 02:46:47 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[RPT_PEDIDO_INTERNO_PARTIDAS]
--DECLARE
	@EMPRESA BIGINT,
	@NO_PEDIDO BIGINT
AS
BEGIN
	SET NOCOUNT ON;
--	SET @EMPRESA = 1
--	SET @NO_PEDIDO = 3006
	DECLARE 
		@CANTIDAD_DIFERENTES_TALLAS DECIMAL

	CREATE TABLE #PARTIDAS
	(
		CVE_CLIENTE BIGINT,
		CVE_PRENDA BIGINT,
		LUGARDEENTREGA BIGINT,
		PARTIDA BIGINT,
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		TELABASE NVARCHAR(max),
		TELACOMBINACION NVARCHAR(MAX),
		LOGOTIPOS NVARCHAR(max)
	)
	INSERT INTO #PARTIDAS
	(
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		PARTIDA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		TELABASE,
		TELACOMBINACION,
		LOGOTIPOS
	)
	SELECT
		PI.Cve_Cliente,
		PIT.Cve_Prenda,
		PIT.LugarDeEntrega,
		PIT.Partida,
		CONVERT(DATE,PIT.FechaVencimiento),
		PIT.Prioridad,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, PEMD.Cve_Tela) + ' (' + CT.Composicion + ')'
			FROM PRENDA_ESTRUCTURA_MATERIALES_DETALLE PEMD,CATALOGO_TELA CT
			WHERE PEMD.Cve_Prenda = PIT.Cve_Prenda AND PEMD.TipoMaterial = 'T' AND PEMD.TipoTela = 'B' AND CT.Cve_Tela = PEMD.Cve_Tela
			GROUP BY PEMD.Cve_Tela,CT.Composicion
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS TelaBase,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, PEMD.Cve_Tela) + ' (' + CT.Composicion + ')'
			FROM PRENDA_ESTRUCTURA_MATERIALES_DETALLE PEMD,CATALOGO_TELA CT
			WHERE PEMD.Cve_Prenda = PIT.Cve_Prenda AND PEMD.TipoMaterial = 'T' AND PEMD.TipoTela = 'C' AND CT.Cve_Tela = PEMD.Cve_Tela
			GROUP BY PEMD.Cve_Tela,CT.Composicion
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS TelaCombinacion,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, PL.Cve_Logotipo) 
			FROM PRENDA_LOGOTIPO PL 
			WHERE PL.Cve_Prenda = PIT.Cve_Prenda
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS Logotipos
	FROM 
		PEDIDO_INTERNO PI,
		PEDIDO_INTERNO_TALLAS PIT
	WHERE 
		PI.Empresa = @EMPRESA
		AND PI.No_Pedido = @NO_PEDIDO
		AND PIT.Empresa = PI.Empresa
		AND PIT.No_Pedido = PI.No_Pedido
	GROUP BY
		PI.Cve_Cliente,
		PIT.Cve_Prenda,
		PIT.LugarDeEntrega,
		PIT.Partida,
		CONVERT(DATE,PIT.FechaVencimiento),
		PIT.Prioridad
		--select * from #PARTIDAS
	CREATE TABLE #TEMP
	(
		CVE_CLIENTE BIGINT,
		CVE_PRENDA BIGINT,
		LUGARDEENTREGA BIGINT,
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		CONSECUTIVO BIGINT,--ESTE SE UTILIZA COMO NÚMERO DE PARTIDA
		CONSECUTIVO1 BIGINT,--ESTE SE UTILIZA COMO CONSECUTIVO DE TALLA
		TELABASE NVARCHAR(MAX),
		TELACOMBINACION NVARCHAR(MAX),
		LOGOTIPOS NVARCHAR(MAX),
		PARTIDA BIGINT,
		TALLA NVARCHAR(50)
	)

	INSERT INTO #TEMP
	(
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		CONSECUTIVO,
		CONSECUTIVO1,
		TELABASE,
		TELACOMBINACION,
		LOGOTIPOS,
		PARTIDA,
		TALLA
	)
	SELECT
		P.CVE_CLIENTE,
		P.CVE_PRENDA,
		P.LUGARDEENTREGA,
		P.FECHAVENCIMIENTO,
		P.PRIORIDAD,
		PIT.Partida,
		ROW_NUMBER() OVER (
        PARTITION BY P.CVE_CLIENTE, P.CVE_PRENDA, P.LUGARDEENTREGA, P.FECHAVENCIMIENTO, P.PRIORIDAD 
        ORDER BY TG.Partida
		) AS NumeroFila,
		P.TELABASE,
		P.TELACOMBINACION,
		P.LOGOTIPOS,
		TG.Partida,
		PIT.Talla
	FROM 
		PEDIDO_INTERNO PI,
		PEDIDO_INTERNO_TALLAS PIT,
		TALLAS_GENERALES TG,
		#PARTIDAS p
	WHERE 
		PI.Empresa = @EMPRESA
	AND PI.No_Pedido = @NO_PEDIDO
	AND PIT.Empresa = PI.Empresa
	AND PIT.No_Pedido = PI.No_Pedido
	AND TG.Talla = PIT.Talla
	AND P.CVE_CLIENTE = PI.Cve_Cliente
	AND P.CVE_PRENDA = PIT.Cve_Prenda
	AND P.LUGARDEENTREGA = PIT.LugarDeEntrega
	AND P.FECHAVENCIMIENTO = CONVERT(DATE,PIT.FechaVencimiento)
	AND P.PRIORIDAD = PIT.Prioridad
	GROUP BY
		P.CVE_CLIENTE,
		P.CVE_PRENDA,
		P.LUGARDEENTREGA,
		P.FECHAVENCIMIENTO,
		P.PRIORIDAD,
		PIT.Partida,
		P.TELABASE,
		P.TELACOMBINACION,
		P.LOGOTIPOS,
		TG.Partida,
		PIT.Talla
	ORDER BY
		P.CVE_CLIENTE,
		P.CVE_PRENDA,
		P.LUGARDEENTREGA,
		P.FECHAVENCIMIENTO,
		P.PRIORIDAD,
		TG.Partida

	CREATE TABLE #PEDIDO_PARTIDAS
	(
		NO_PEDIDO BIGINT,
		CVE_PRENDA NUMERIC(18,0),
		DESCRIPCIONPRENDA NVARCHAR(1000),
		TELABASE NVARCHAR(MAX),
		TELACOMBINACION NVARCHAR(MAX),
		LOGOTIPOS NVARCHAR(MAX),
		LUGARDEENTREGA NUMERIC(18,0),
		NOMBRELUGARDEENTREGA NVARCHAR(1000),
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		MOTIVOPRIORIDAD NVARCHAR(1000),
		PARTIDA BIGINT,
		TALLA NVARCHAR(50),
		CANTIDAD NUMERIC(18,0),
		PRECIO NUMERIC(18,4),
		PORCENTAJE_IVA NUMERIC(18,2),
		OBSERVACIONES_PARTIDAPRODUCCION NVARCHAR(MAX),
		OBSERVACIONES_PARTIDALOGISTICA NVARCHAR(MAX),
		OBSERVACIONES_PARTIDAFACTURACION NVARCHAR(MAX)
	)

	CREATE TABLE #PEDIDO
	(
		NO_PEDIDO BIGINT,
		CVE_PRENDA NUMERIC(18,0),
		DESCRIPCIONPRENDA NVARCHAR(1000),
		TELABASE NVARCHAR(MAX),
		TELACOMBINACION NVARCHAR(MAX),
		LOGOTIPOS NVARCHAR(MAX),
		LUGARDEENTREGA NUMERIC(18,0),
		NOMBRELUGARDEENTREGA NVARCHAR(1000),
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		MOTIVOPRIORIDAD NVARCHAR(1000),
		PARTIDA BIGINT,
		CONSECUTIVO BIGINT,
		TALLA1 NVARCHAR(50),
		TALLA2 NVARCHAR(50),
		TALLA3 NVARCHAR(50),
		TALLA4 NVARCHAR(50),
		TALLA5 NVARCHAR(50),
		TALLA6 NVARCHAR(50),
		TALLA7 NVARCHAR(50),
		TALLA8 NVARCHAR(50),
		TALLA9 NVARCHAR(50),
		TALLA10 NVARCHAR(50),
		TALLA11 NVARCHAR(50),
		TALLA12 NVARCHAR(50),
		TALLA13 NVARCHAR(50),
		PRECIO NUMERIC(18,4),
		PORCENTAJE_IVA NUMERIC(18,2),
		PRENDAS_TOTALES_PARTIDA BIGINT,
		SUBTOTAL_PARTIDA NUMERIC(18,4),
		IVA_PARTIDA NUMERIC(18,4),
		TOTAL_PARTIDA NUMERIC(18,4),
		PRENDAS_TOTALES_PEDIDO BIGINT,
		SUBTOTAL_PEDIDO NUMERIC(18,4),
		IVA_PEDIDO NUMERIC(18,4),
		TOTAL_PEDIDO NUMERIC(18,4),
		OBSERVACIONES_PARTIDAPRODUCCION NVARCHAR(MAX),
		OBSERVACIONES_PARTIDALOGISTICA NVARCHAR(MAX),
		OBSERVACIONES_PARTIDAFACTURACION NVARCHAR(MAX)
	)

	INSERT INTO #PEDIDO_PARTIDAS
	(
		NO_PEDIDO,
		CVE_PRENDA,
		DESCRIPCIONPRENDA,
		TELABASE,
		TELACOMBINACION,
		LOGOTIPOS,
		LUGARDEENTREGA,
		NOMBRELUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		MOTIVOPRIORIDAD,
		PARTIDA,
		TALLA,
		CANTIDAD,
		PRECIO,
		PORCENTAJE_IVA,
		OBSERVACIONES_PARTIDAPRODUCCION,
		OBSERVACIONES_PARTIDALOGISTICA,
		OBSERVACIONES_PARTIDAFACTURACION
	)
	SELECT 
		PI.No_Pedido,
		PIT.Cve_Prenda,
		PIT.DescripcionPrenda,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, PEMD.Cve_Tela) + ' (' + CT.Composicion + ')'
			FROM PRENDA_ESTRUCTURA_MATERIALES_DETALLE PEMD,CATALOGO_TELA CT
			WHERE PEMD.Cve_Prenda = PIT.Cve_Prenda AND PEMD.TipoMaterial = 'T' AND PEMD.TipoTela = 'B' AND CT.Cve_Tela = PEMD.Cve_Tela
			GROUP BY PEMD.Cve_Tela,CT.Composicion
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS TelaBase,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, PEMD.Cve_Tela) + ' (' + CT.Composicion + ')'
			FROM PRENDA_ESTRUCTURA_MATERIALES_DETALLE PEMD,CATALOGO_TELA CT
			WHERE PEMD.Cve_Prenda = PIT.Cve_Prenda AND PEMD.TipoMaterial = 'T' AND PEMD.TipoTela = 'C' AND CT.Cve_Tela = PEMD.Cve_Tela
			GROUP BY PEMD.Cve_Tela,CT.Composicion
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS TelaCombinacion,
		STUFF(
		(
			SELECT ', ' + CONVERT(NVARCHAR, ISNULL(PL.Cve_Logotipo,'')) 
			FROM PRENDA_LOGOTIPO PL 
			WHERE PL.Cve_Prenda = PIT.Cve_Prenda
			FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)'), 
		1, 2, ''
		) AS Logotipos,
		PIT.LugarDeEntrega,
		PIT.NombreLugarDeEntrega,
		PIT.FechaVencimiento,
		PIT.Prioridad,
		PIT.MotivoPrioridad,
		PIT.Partida,
		PIT.Talla,
		PIT.Cantidad,
		PIT.PrecioUnitario,
		PI.PorcentajeIVA,
		PIT.ObservacionesPartidaProduccion,
		PIT.ObservacionesPartidaLogistica,
		PIT.ObservacionesPartidaFacturacion
	FROM 
		PEDIDO_INTERNO PI,
		PEDIDO_INTERNO_TALLAS PIT,
		TALLAS_GENERALES TG
	WHERE 
		PI.Empresa = @EMPRESA
	AND PI.No_Pedido = @NO_PEDIDO
	AND PIT.Empresa = PI.Empresa
	AND PIT.No_Pedido = PI.No_Pedido
	AND TG.Talla = PIT.Talla

	DECLARE @sql AS NVARCHAR(MAX);

	CREATE TABLE #RELLENO
	(
		CONSECUTIVO INT,
		RELLENO NVARCHAR(100)
	)

	INSERT INTO #RELLENO VALUES(1,'[100],')
	INSERT INTO #RELLENO VALUES(2,'[100],[101],')
	INSERT INTO #RELLENO VALUES(3,'[100],[101],[102],')
	INSERT INTO #RELLENO VALUES(4,'[100],[101],[102],[103],')
	INSERT INTO #RELLENO VALUES(5,'[100],[101],[102],[103],[104],')
	INSERT INTO #RELLENO VALUES(6,'[100],[101],[102],[103],[104],[105],')
	INSERT INTO #RELLENO VALUES(7,'[100],[101],[102],[103],[104],[105],[106],')
	INSERT INTO #RELLENO VALUES(8,'[100],[101],[102],[103],[104],[105],[106],[107],')
	INSERT INTO #RELLENO VALUES(9,'[100],[101],[102],[103],[104],[105],[106],[107],[108],')
	INSERT INTO #RELLENO VALUES(10,'[100],[101],[102],[103],[104],[105],[106],[107],[108],[109],')
	INSERT INTO #RELLENO VALUES(11,'[100],[101],[102],[103],[104],[105],[106],[107],[108],[109],[110],')
	INSERT INTO #RELLENO VALUES(12,'[100],[101],[102],[103],[104],[105],[106],[107],[108],[109],[110],[111],')
	INSERT INTO #RELLENO VALUES(13,'[100],[101],[102],[103],[104],[105],[106],[107],[108],[109],[110],[111],[112],')

	--SELECT @cols = (
	--	SELECT QUOTENAME(talla) + ', '
	--	FROM #TEMP
	--	FOR XML PATH('')
	--);
	--	SELECT (
	--	SELECT QUOTENAME(talla) + ', '
	--	FROM #TEMP T, #PARTIDAS P
	--	WHERE T.CVE_CLIENTE = P.CVE_CLIENTE AND T.CVE_PRENDA = P.CVE_PRENDA AND T.LUGARDEENTREGA = P.LUGARDEENTREGA AND T.FECHAVENCIMIENTO = P.FECHAVENCIMIENTO
	--	GROUP BY T.CVE_CLIENTE,T.CVE_PRENDA,T.LUGARDEENTREGA,T.FECHAVENCIMIENTO,T.PRIORIDAD,T.TALLA
	--	FOR XML PATH('')
	--);
	CREATE TABLE #TEMP2
	(
		CVE_CLIENTE BIGINT,
		CVE_PRENDA BIGINT,
		LUGARDEENTREGA BIGINT,
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		CANTIDAD_TALLAS BIGINT
	)
	INSERT INTO #TEMP2
	(
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		CANTIDAD_TALLAS
	)
	SELECT 
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		COUNT(*) 
	FROM 
		#TEMP 
	GROUP BY 
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD

	CREATE TABLE #TEMP3
	(
		PARTIDA BIGINT,
		CVE_CLIENTE BIGINT,
		CVE_PRENDA BIGINT,
		LUGARDEENTREGA BIGINT,
		FECHAVENCIMIENTO DATE,
		PRIORIDAD BIGINT,
		CANT_MAX_TALLAS BIGINT,
		QUERYTALLAS NVARCHAR(MAX)
	)

	SELECT @CANTIDAD_DIFERENTES_TALLAS = MAX(CANTIDAD_TALLAS) FROM #TEMP2

	SELECT @CANTIDAD_DIFERENTES_TALLAS = CEILING(@CANTIDAD_DIFERENTES_TALLAS/13)

	DECLARE @CONTADOR AS INT = 1
	DECLARE @INICIAL AS INT
	DECLARE @FINAL AS INT
	--SELECT * FROM #TEMP
	--SELECT * FROM #PARTIDAS
	--SELECT * FROM #TEMP2
	SET @INICIAL = 1
	SET @FINAL = @INICIAL+12
	WHILE @CONTADOR <= @CANTIDAD_DIFERENTES_TALLAS
	BEGIN
		--select @INICIAL as inicial,@FINAL as final
		INSERT INTO #TEMP3
		(	
			PARTIDA,
			CVE_CLIENTE,
			CVE_PRENDA,
			LUGARDEENTREGA,
			FECHAVENCIMIENTO,
			PRIORIDAD,
			CANT_MAX_TALLAS,
			QUERYTALLAS
		)
		SELECT 
		--@CONTADOR AS PARTIDA,
		P.PARTIDA,
		P.CVE_CLIENTE, 
		P.CVE_PRENDA, 
		P.LUGARDEENTREGA, 
		P.FECHAVENCIMIENTO,
		P.PRIORIDAD,
		(SELECT COUNT(*) FROM #TEMP T1 WHERE T1.CVE_CLIENTE = P.CVE_CLIENTE AND T1.CVE_PRENDA = P.CVE_PRENDA AND T1.LUGARDEENTREGA = P.LUGARDEENTREGA AND T1.FECHAVENCIMIENTO = P.FECHAVENCIMIENTO AND T1.PRIORIDAD = P.PRIORIDAD AND T1.CONSECUTIVO1 >= @INICIAL AND T1.CONSECUTIVO1 <=@FINAL),---ESTO ES PARA QUE ME SUME LA CANTIDAD DE TALLAS QUE ESTA METIENDO EN ESA PARTIDA PARA USAR EN EL RELLENO
		--T2.CANTIDAD_TALLAS,---ESTO SE SUSTITUYO POR LA LINEA DE ARRIBA
		(SELECT QUOTENAME(T.talla) + ', '
		--(SELECT T.talla + ', '
		 FROM #TEMP T
		 WHERE T.CVE_CLIENTE = P.CVE_CLIENTE AND T.CVE_PRENDA = P.CVE_PRENDA AND T.LUGARDEENTREGA = P.LUGARDEENTREGA AND T.FECHAVENCIMIENTO = P.FECHAVENCIMIENTO AND T.PRIORIDAD = P.PRIORIDAD AND T.CONSECUTIVO1 >= @INICIAL AND T.CONSECUTIVO1 <=@FINAL
		 GROUP BY T.CVE_CLIENTE, T.CVE_PRENDA, T.LUGARDEENTREGA, T.FECHAVENCIMIENTO, T.PRIORIDAD, T.TALLA,T.PARTIDA
		 ORDER BY T.PARTIDA
		 FOR XML PATH('')
		) AS Tallas
		FROM #PARTIDAS P,
			#TEMP2 T2
		WHERE
			T2.CVE_CLIENTE = P.CVE_CLIENTE AND T2.CVE_PRENDA = P.CVE_PRENDA AND T2.LUGARDEENTREGA = P.LUGARDEENTREGA AND T2.FECHAVENCIMIENTO = P.FECHAVENCIMIENTO AND T2.PRIORIDAD = P.PRIORIDAD
		--GROUP BY 
		--	P.PARTIDA,
		--	P.CVE_CLIENTE, 
		--	P.CVE_PRENDA, 
		--	P.LUGARDEENTREGA, 
		--	P.FECHAVENCIMIENTO,
		--	P.PRIORIDAD

		SET @INICIAL = @FINAL+1
		SET @FINAL = @INICIAL+12
	
		SET @CONTADOR+=1
	END
	
	DELETE #TEMP3 WHERE QUERYTALLAS IS NULL
	--SELECT * FROM #TEMP3
	UPDATE
		#TEMP3
	SET	
		QUERYTALLAS = QUERYTALLAS + R.RELLENO--REPLICATE(QUOTENAME('NULL') + ', ',13-CANT_MAX_TALLAS) 
	FROM
		#TEMP3 T,
		#RELLENO R
	WHERE
		CANT_MAX_TALLAS < 13
	AND R.CONSECUTIVO = 13-CANT_MAX_TALLAS

	UPDATE
		#TEMP3
	SET	
		QUERYTALLAS = QUERYTALLAS + R.RELLENO --REPLICATE(QUOTENAME('NULL') + ', ',13-(CANT_MAX_TALLAS-13)) 
	FROM
		#TEMP3 T,
		#RELLENO R
	WHERE
		T.CANT_MAX_TALLAS > 13
	AND T.PARTIDA = CEILING(CONVERT(DECIMAL,CANT_MAX_TALLAS)/13)
	AND R.CONSECUTIVO = 13-(CANT_MAX_TALLAS-13)


	UPDATE
		#TEMP3
	SET	QUERYTALLAS = LEFT(QUERYTALLAS, LEN(QUERYTALLAS) - 1) FROM #TEMP3

	--SELECT * FROM #TEMP
	--SELECT * FROM #TEMP2
	--SELECT * FROM #TEMP3

	DECLARE 
		@PARTIDA_CURSOR BIGINT,
		@CVE_CLIENTE_CURSOR BIGINT,
		@CVE_PRENDA_CURSOR BIGINT,
		@LUGARDEENTREGA_CURSOR BIGINT,
		@FECHAVENCIMIENTO_CURSOR DATE,
		@PRIORIDAD_CURSOR BIGINT,
		@CANT_MAX_TALLAS_CURSOR BIGINT,
		@QUERYTALLAS NVARCHAR(MAX),
		@PARTIDA_ANTERIOR AS BIGINT,
		@CONSECUTIVOPARTIDA AS BIGINT

	SET @PARTIDA_ANTERIOR = 0
	SET @CONSECUTIVOPARTIDA = 0

	DECLARE PARTIDASPEDIDO CURSOR FOR
	SELECT
		PARTIDA,
		CVE_CLIENTE,
		CVE_PRENDA,
		LUGARDEENTREGA,
		FECHAVENCIMIENTO,
		PRIORIDAD,
		CANT_MAX_TALLAS,
		QUERYTALLAS
	FROM
		#TEMP3
	ORDER BY
		PARTIDA
	OPEN PARTIDASPEDIDO
	FETCH NEXT FROM PARTIDASPEDIDO INTO @PARTIDA_CURSOR,@CVE_CLIENTE_CURSOR,@CVE_PRENDA_CURSOR,@LUGARDEENTREGA_CURSOR,@FECHAVENCIMIENTO_CURSOR,@PRIORIDAD_CURSOR,@CANT_MAX_TALLAS_CURSOR,@QUERYTALLAS
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @PARTIDA_ANTERIOR = @PARTIDA_CURSOR
		BEGIN
			SET @CONSECUTIVOPARTIDA +=1
		END
		ELSE
		BEGIN
			SET @CONSECUTIVOPARTIDA = 1
		END
		--SELECT @CONSECUTIVOPARTIDA,@PARTIDA_CURSOR
		SET @sql = 'SELECT 
			  NO_PEDIDO,
			  CVE_PRENDA,
			  DESCRIPCIONPRENDA,
			  TELABASE,
			  TELACOMBINACION,
			  LOGOTIPOS,
			  LUGARDEENTREGA,
			  NOMBRELUGARDEENTREGA,
			  FECHAVENCIMIENTO,
			  PRIORIDAD,
			  MOTIVOPRIORIDAD,
			  PARTIDA,
			  ' + CONVERT(nvarchar,@CONSECUTIVOPARTIDA) + ',
			  ' + @QUERYTALLAS + ',
			  PRECIO,
			  PORCENTAJE_IVA,
			  OBSERVACIONES_PARTIDAPRODUCCION,
			  OBSERVACIONES_PARTIDALOGISTICA,
			  OBSERVACIONES_PARTIDAFACTURACION
			FROM 
			(
			  SELECT 
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				PARTIDA,
				talla AS talla_column,
				MAX(TALLA) AS TALLA_total,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			  FROM #PEDIDO_PARTIDAS
			  WHERE	CVE_PRENDA = ' + CONVERT(NVARCHAR,@CVE_PRENDA_CURSOR) + '
			  AND LUGARDEENTREGA = ' + CONVERT(NVARCHAR,@LUGARDEENTREGA_CURSOR) + '
			  AND PRIORIDAD = ' + CONVERT(NVARCHAR,@PRIORIDAD_CURSOR) + '
			  GROUP BY 
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				PARTIDA,
				TALLA,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			) x
			PIVOT 
			(
			  MAX(TALLA_total)
			  FOR talla_column IN (' + @QUERYTALLAS + ')
			) p';
			--select @sql
			--SELECT NO_PEDIDO,CVE_PRENDA,DESCRIPCIONPRENDA,TELABASE,LOGOTIPOS,LUGARDEENTREGA,NOMBRELUGARDEENTREGA,FECHAVENCIMIENTO,PRIORIDAD,MOTIVOPRIORIDAD,PARTIDA,1,[26], [28], [30], [32], [34], [36], [38], [40], [42], [44], [46], [48], [50], [52], [54], [60],PRECIO,PORCENTAJE_IVA,OBSERVACIONES_PARTIDAPRODUCCION,OBSERVACIONES_PARTIDALOGISTICA,OBSERVACIONES_PARTIDAFACTURACION FROM (SELECT NO_PEDIDO,CVE_PRENDA,DESCRIPCIONPRENDA,TELABASE,LOGOTIPOS,LUGARDEENTREGA,NOMBRELUGARDEENTREGA,FECHAVENCIMIENTO,PRIORIDAD,MOTIVOPRIORIDAD,PARTIDA,talla AS talla_column,MAX(TALLA) AS TALLA_total,PRECIO,PORCENTAJE_IVA,OBSERVACIONES_PARTIDAPRODUCCION,OBSERVACIONES_PARTIDALOGISTICA,OBSERVACIONES_PARTIDAFACTURACION FROM #PEDIDO_PARTIDAS WHERE CVE_PRENDA = 7202 AND LUGARDEENTREGA = 3226 AND PRIORIDAD = 1 GROUP BY NO_PEDIDO,CVE_PRENDA,DESCRIPCIONPRENDA,TELABASE,LOGOTIPOS,LUGARDEENTREGA,NOMBRELUGARDEENTREGA,FECHAVENCIMIENTO,PRIORIDAD,MOTIVOPRIORIDAD,PARTIDA,TALLA,PRECIO,PORCENTAJE_IVA,OBSERVACIONES_PARTIDAPRODUCCION,OBSERVACIONES_PARTIDALOGISTICA,OBSERVACIONES_PARTIDAFACTURACION) x PIVOT (MAX(TALLA_total) FOR talla_column IN ([26], [28], [30], [32], [34], [36], [38], [40], [42], [44], [46], [48], [50], [52], [54], [60])) p
			INSERT INTO #PEDIDO
			(
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				PARTIDA,
				CONSECUTIVO,
				TALLA1,
				TALLA2,
				TALLA3,
				TALLA4,
				TALLA5,
				TALLA6,
				TALLA7,
				TALLA8,
				TALLA9,
				TALLA10,
				TALLA11,
				TALLA12,
				TALLA13,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			)
			EXEC sp_executesql @SQL
		
		SET @CONSECUTIVOPARTIDA +=1
		--SELECT @CONSECUTIVOPARTIDA,@PARTIDA_CURSOR
		SET @sql = 'SELECT 
			  NO_PEDIDO,
			  CVE_PRENDA,
			  DESCRIPCIONPRENDA,
			  TELABASE,
			  TELACOMBINACION,
			  LOGOTIPOS,
			  LUGARDEENTREGA,
			  NOMBRELUGARDEENTREGA,
			  FECHAVENCIMIENTO,
			  PRIORIDAD,
			  MOTIVOPRIORIDAD,'
			  + CONVERT(NVARCHAR,@PARTIDA_CURSOR) + ',
			  ' + CONVERT(NVARCHAR,@CONSECUTIVOPARTIDA) + ',
			  ' + @QUERYTALLAS + ',
			  PRECIO,
			  PORCENTAJE_IVA,
			  OBSERVACIONES_PARTIDAPRODUCCION,
			  OBSERVACIONES_PARTIDALOGISTICA,
			  OBSERVACIONES_PARTIDAFACTURACION
			FROM 
			(
			  SELECT 
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				talla AS talla_column,
				SUM(cantidad) AS cantidad_total,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			  FROM #PEDIDO_PARTIDAS
			  WHERE	CVE_PRENDA = ' + CONVERT(NVARCHAR,@CVE_PRENDA_CURSOR) + '
			  AND LUGARDEENTREGA = ' + CONVERT(NVARCHAR,@LUGARDEENTREGA_CURSOR) + '
			  AND PRIORIDAD = ' + CONVERT(NVARCHAR,@PRIORIDAD_CURSOR) + '
			  GROUP BY 
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				TALLA,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			) x
			PIVOT 
			(
			  SUM(cantidad_total)
			  FOR talla_column IN (' + @QUERYTALLAS + ')
			) p';

			INSERT INTO #PEDIDO
			(
				NO_PEDIDO,
				CVE_PRENDA,
				DESCRIPCIONPRENDA,
				TELABASE,
				TELACOMBINACION,
				LOGOTIPOS,
				LUGARDEENTREGA,
				NOMBRELUGARDEENTREGA,
				FECHAVENCIMIENTO,
				PRIORIDAD,
				MOTIVOPRIORIDAD,
				PARTIDA,
				CONSECUTIVO,
				TALLA1,
				TALLA2,
				TALLA3,
				TALLA4,
				TALLA5,
				TALLA6,
				TALLA7,
				TALLA8,
				TALLA9,
				TALLA10,
				TALLA11,
				TALLA12,
				TALLA13,
				PRECIO,
				PORCENTAJE_IVA,
				OBSERVACIONES_PARTIDAPRODUCCION,
				OBSERVACIONES_PARTIDALOGISTICA,
				OBSERVACIONES_PARTIDAFACTURACION
			)
			EXEC sp_executesql @SQL
			SET @PARTIDA_ANTERIOR = @PARTIDA_CURSOR

			FETCH NEXT FROM PARTIDASPEDIDO INTO @PARTIDA_CURSOR,@CVE_CLIENTE_CURSOR,@CVE_PRENDA_CURSOR,@LUGARDEENTREGA_CURSOR,@FECHAVENCIMIENTO_CURSOR,@PRIORIDAD_CURSOR,@CANT_MAX_TALLAS_CURSOR,@QUERYTALLAS
	END
	CLOSE PARTIDASPEDIDO
	DEALLOCATE PARTIDASPEDIDO
	
	--SET @sql = 'SELECT 
	--			  NO_PEDIDO,
	--			  CVE_PRENDA,
	--			  DESCRIPCIONPRENDA,
	--			  LUGARDEENTREGA,
	--			  NOMBRELUGARDEENTREGA,
	--			  FECHAVENCIMIENTO,
	--			  PRIORIDAD,
	--			  MOTIVOPRIORIDAD,
	--			  ' + @cols + ',
	--			  PRECIO,
	--			  OBSERVACIONES_PARTIDAPRODUCCION,
	--			  OBSERVACIONES_PARTIDALOGISTICA,
	--			  OBSERVACIONES_PARTIDAFACTURACION
	--			FROM 
	--			(
	--			  SELECT 
	--				NO_PEDIDO,
	--				CVE_PRENDA,
	--				DESCRIPCIONPRENDA,
	--				LUGARDEENTREGA,
	--				NOMBRELUGARDEENTREGA,
	--				FECHAVENCIMIENTO,
	--				PRIORIDAD,
	--				MOTIVOPRIORIDAD,
	--				talla AS talla_column,
	--				SUM(cantidad) AS cantidad_total,
	--				PRECIO,
	--				OBSERVACIONES_PARTIDAPRODUCCION,
	--				OBSERVACIONES_PARTIDALOGISTICA,
	--				OBSERVACIONES_PARTIDAFACTURACION
	--			  FROM #PEDIDO_PARTIDAS
	--			  GROUP BY 
	--				NO_PEDIDO,
	--				CVE_PRENDA,
	--				DESCRIPCIONPRENDA,
	--				LUGARDEENTREGA,
	--				NOMBRELUGARDEENTREGA,
	--				FECHAVENCIMIENTO,
	--				PRIORIDAD,
	--				MOTIVOPRIORIDAD,
	--				TALLA,
	--				PRECIO,
	--				OBSERVACIONES_PARTIDAPRODUCCION,
	--				OBSERVACIONES_PARTIDALOGISTICA,
	--				OBSERVACIONES_PARTIDAFACTURACION
	--			) x
	--			PIVOT 
	--			(
	--			  SUM(cantidad_total)
	--			  FOR talla_column IN (' + @cols + ')
	--			) p';

	--EXEC sp_executesql @sql;
	    -- Insert statements for procedure here
	--SELECT
	--	PI.Empresa,
	--	PI.No_Pedido,
	--	PI.Num_Folio,
	--	PI.Cve_Cliente,
	--	PI.Nom_Cliente,
	--	FA.Cve_PedCliente,
	--	FA.Contrato_Cliente,
	--	FA.Cve_Proveedor,
	--	FA.Orden_Surtimiento,
	--	PIT.Cve_Prenda,
	--	PIT.DescripcionPrenda,
	--	PIT.LugarDeEntrega,
	--	PIT.NombreLugarDeEntrega,
	--	PIT.FechaVencimiento,
	--	TG.Partida,
	--	PIT.Talla,
	--	PIT.Cantidad
	--FROM
	--	FOLIOS_ADMINISTRACION FA,
	--	PEDIDO_INTERNO PI,
	--	PEDIDO_INTERNO_TALLAS PIT,
	--	TALLAS_GENERALES TG
	--WHERE
	--	PI.Empresa = @EMPRESA
	--AND PI.No_Pedido = @NO_PEDIDO
	--AND FA.Empresa = PI.Empresa
	--AND FA.Num_Folio = PI.Num_Folio
	--AND PIT.Empresa = PI.Empresa
	--AND PIT.No_Pedido = PI.No_Pedido
	--AND TG.Talla = PIT.Talla

	--ACTUALIZA EL TOTAL DE CADA PARTIDA
	UPDATE
		#PEDIDO
	SET
		PRENDAS_TOTALES_PARTIDA = (SELECT ISNULL(SUM(PP.CANTIDAD),0) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO AND PP.CVE_PRENDA = #PEDIDO.CVE_PRENDA AND PP.LUGARDEENTREGA = #PEDIDO.LUGARDEENTREGA AND PP.FECHAVENCIMIENTO = #PEDIDO.FECHAVENCIMIENTO AND PP.PRIORIDAD = #PEDIDO.PRIORIDAD),
		SUBTOTAL_PARTIDA = (SELECT ISNULL(SUM(PP.CANTIDAD),0)*#PEDIDO.PRECIO FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO AND PP.CVE_PRENDA = #PEDIDO.CVE_PRENDA AND PP.LUGARDEENTREGA = #PEDIDO.LUGARDEENTREGA AND PP.FECHAVENCIMIENTO = #PEDIDO.FECHAVENCIMIENTO AND PP.PRIORIDAD = #PEDIDO.PRIORIDAD),
		IVA_PARTIDA = (SELECT (ISNULL(SUM(PP.CANTIDAD),0)*#PEDIDO.PRECIO)*(#PEDIDO.PORCENTAJE_IVA/100) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO AND PP.CVE_PRENDA = #PEDIDO.CVE_PRENDA AND PP.LUGARDEENTREGA = #PEDIDO.LUGARDEENTREGA AND PP.FECHAVENCIMIENTO = #PEDIDO.FECHAVENCIMIENTO AND PP.PRIORIDAD = #PEDIDO.PRIORIDAD),
		TOTAL_PARTIDA = (SELECT (ISNULL(SUM(PP.CANTIDAD),0)*#PEDIDO.PRECIO)*((#PEDIDO.PORCENTAJE_IVA/100)+1) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO AND PP.CVE_PRENDA = #PEDIDO.CVE_PRENDA AND PP.LUGARDEENTREGA = #PEDIDO.LUGARDEENTREGA AND PP.FECHAVENCIMIENTO = #PEDIDO.FECHAVENCIMIENTO AND PP.PRIORIDAD = #PEDIDO.PRIORIDAD),
		PRENDAS_TOTALES_PEDIDO = (SELECT ISNULL(SUM(PP.CANTIDAD),0) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO),
		SUBTOTAL_PEDIDO = (SELECT ISNULL(SUM(PP.CANTIDAD*PP.PRECIO),0) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO),
		IVA_PEDIDO = (SELECT (ISNULL(SUM(PP.CANTIDAD*PP.PRECIO),0))*(#PEDIDO.PORCENTAJE_IVA/100) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO),
		TOTAL_PEDIDO = (SELECT (ISNULL(SUM(PP.CANTIDAD*PP.PRECIO),0))*((#PEDIDO.PORCENTAJE_IVA/100)+1) FROM #PEDIDO_PARTIDAS PP WHERE PP.NO_PEDIDO = #PEDIDO.NO_PEDIDO)

	SELECT
		--DENSE_RANK() OVER (
  --      ORDER BY P.CVE_PRENDA
		--) AS Ptda,
		P.NO_PEDIDO,
		P.PARTIDA,
		CASE FA.TipoPedido 
			WHEN 'N' THEN 'CONFECCIÓN' 
			WHEN 'C' THEN 'COMPRA'
			WHEN 'M' THEN 'MUESTRA'
			WHEN 'L' THEN 'FACTURACIÓN'
			ELSE '' END AS TIPO_PEDIDO,
		PI.FECHAHORA AS FECHA_PEDIDO,
		PI.Cve_Cliente,
		PI.Nom_Cliente,
		C.RFC,
		C.Calle,
		C.Colonia,
		C.CP,
		C.Ciudad,
		C.Estado,
		C.Municipio,
		C.Ciudad,
		C.Estado,
		C.Telefono,
		PI.LlevaInspeccion,
		PI.LugarInspeccion,
		PI.QuienInspecciona,
		PI.HorarioInspeccion,
		PI.AdmitenEntregaParcial,
		PI.PorcentajeSancionDiaria,
		PI.PorcentajeSancionMaxima,
		FA.Contrato_Cliente,
		FA.Cve_PedCliente,
		FA.Cve_Proveedor,
		FA.Orden_Surtimiento,
		PI.CondicionesPagoDias,
		PI.CondicionesPagoTipoDias,
		PI.CondicionesPagoCondicion,
		PI.RegimenFiscal,
		PI.UsoCFDI,
		PI.MetodoPago,
		PI.FormaPago,
		PI.BancoPago,
		PI.CuentaPago,
		P.CVE_PRENDA,
		P.DESCRIPCIONPRENDA,
		P.TELABASE,
		P.TELACOMBINACION,
		P.LOGOTIPOS,
		P.LUGARDEENTREGA,
		P.NOMBRELUGARDEENTREGA,
		P.FECHAVENCIMIENTO,
		P.PRIORIDAD,
		P.MOTIVOPRIORIDAD,
		P.CONSECUTIVO,
		P.TALLA1,
		P.TALLA2,
		P.TALLA3,
		P.TALLA4,
		P.TALLA5,
		P.TALLA6,
		P.TALLA7,
		P.TALLA8,
		P.TALLA9,
		P.TALLA10,
		P.TALLA11,
		P.TALLA12,
		P.TALLA13,
		P.PRECIO,
		P.PORCENTAJE_IVA,
		P.PRENDAS_TOTALES_PARTIDA,
		P.SUBTOTAL_PARTIDA,
		P.IVA_PARTIDA,
		P.TOTAL_PARTIDA,
		P.PRENDAS_TOTALES_PEDIDO,
		P.SUBTOTAL_PEDIDO,
		P.IVA_PEDIDO,
		P.TOTAL_PEDIDO,
		P.OBSERVACIONES_PARTIDAPRODUCCION,
		P.OBSERVACIONES_PARTIDALOGISTICA,
		P.OBSERVACIONES_PARTIDAFACTURACION,
		PI.ObservacionesGeneralesProduccion,
		PI.ObservacionesGeneralesLogistica,
		PI.ObservacionesGeneralesFacturacion
	FROM 
		#PEDIDO P,
		FOLIOS_ADMINISTRACION FA,
		PEDIDO_INTERNO PI,
		CLIENTES C
	WHERE
		PI.NO_PEDIDO = P.No_Pedido
	AND FA.Num_Folio = PI.Num_Folio
	AND C.Cve_Cliente = PI.Cve_Cliente
	ORDER BY 
		P.NO_PEDIDO,
		P.PARTIDA,
		P.CVE_PRENDA,
		P.LUGARDEENTREGA,
		P.PRIORIDAD,
		P.CONSECUTIVO
	
	drop table #PEDIDO_PARTIDAS
	drop table #TEMP
	drop table #PARTIDAS
	drop table #TEMP2
	DROP TABLE #TEMP3
	DROP TABLE #RELLENO
	DROP TABLE #PEDIDO
END

--exec RPT_PEDIDO_INTERNO_PARTIDAS 1,2156
--SELECT * FROM FOLIOS_ADMINISTRACION
GO

