USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CONSULTA_AVANCE_OP_DETALLE]    Script Date: 04/07/2025 01:55:55 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CONSULTA_AVANCE_OP_DETALLE]
--	DECLARE
		@EMPRESA AS BIGINT,
		@NO_OP AS BIGINT
AS
BEGIN
--	SET @EMPRESA = 1
--	SET	@NO_OP = 678

	--CREACIÓN DE TABLAS AUXILIARES

	--TABLA PARA OBTENER LA CANTIDAD DE TALLAS DE LA OP
	CREATE TABLE #TALLASOP(
		EMPRESA BIGINT,
		CONSECUTIVO INT IDENTITY(1,1),
		PARTIDA INT,
		TALLA NVARCHAR(25),
		CANTIDAD BIGINT
	)
	INSERT INTO #TALLASOP(
		EMPRESA,
		PARTIDA,
		TALLA,
		CANTIDAD
	)
	SELECT 
		PIT.Empresa,
		PEM.Partida,
		PEM.Talla,
		SUM(PIT.Cantidad) AS Cantidad
	FROM 
		PEDIDO_INTERNO_TALLAS PIT,
		PRENDA_ESTRUCTURA_MATERIALES PEM
	WHERE
		PIT.Empresa = @EMPRESA
	AND PIT.No_OP = @NO_OP
	AND PEM.Cve_Prenda = PIT.Cve_Prenda
	AND PEM.Talla = PIT.Talla
	GROUP BY
		PIT.Empresa,
		PEM.Partida,
		PEM.Talla
	ORDER BY
		PEM.Partida

	--TABLA PARA GUARDAR AVANCES DE TM_MOLDE
	CREATE TABLE #AVANCETM_MOLDE(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT
	)

	INSERT INTO #AVANCETM_MOLDE(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTMMTM.Talla,
		OPTMMTM.NoMedida,
		OPTMMTM.Terminado
	FROM
		OP_ASIGNACION OPA,
		OP_TM_MOLDE_TOMA_MEDIDA OPTMMTM
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.No_OP = @NO_OP
	AND OPA.Asignada = 1
	AND OPA.Cancelada = 0
	AND OPA.Empresa = OPTMMTM.Empresa
	AND OPA.No_OP = OPTMMTM.OP
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTMMTM.Talla,
		OPTMMTM.NoMedida,
		OPTMMTM.Terminado
	
	--TABLA PARA GUARDAR AVANCES DE TABLA_MEDIDA ANTES DE PROCESO
	CREATE TABLE #AVANCETM_AP(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT
	)

	INSERT INTO #AVANCETM_AP(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTMAP.Talla,
		OPTMAP.NoMedida,
		OPTMAP.Terminado
	FROM
		OP_ASIGNACION OPA,
		OP_TABLA_MEDIDAAP_TOMA_MEDIDA OPTMAP
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.No_OP = @NO_OP
	AND OPA.Asignada = 1
	AND OPA.Cancelada = 0
	AND OPA.Empresa = OPTMAP.Empresa
	AND OPA.No_OP = OPTMAP.OP
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTMAP.Talla,
		OPTMAP.NoMedida,
		OPTMAP.Terminado


	--TABLA PARA GUARDAR AVANCES DE TABLA_MEDIDA
	CREATE TABLE #AVANCETM(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT
	)

	INSERT INTO #AVANCETM(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado
	FROM
		OP_ASIGNACION OPA,
		OP_TABLA_MEDIDA_TOMA_MEDIDA OPTM
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.No_OP = @NO_OP
	AND OPA.Asignada = 1
	AND OPA.Cancelada = 0
	AND OPTM.Empresa = OPA.Empresa
	AND OPA.No_OP = OPTM.OP
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado

	--TABLA CANTIDAD DE MUETRAS A MEDIR CUANDO NO HAY TABLA DE MEDIDA
	CREATE TABLE #TEMP
	(
		Empresa bigint,
		NO_OP NUMERIC(18,0),
		ORDEN INT,
		NIVEL1 INT,
		NIVEL2 INT,
		NIVEL3 INT,
		PROCESO NVARCHAR(150),
		TALLA NVARCHAR(20), 
		CANTIDAD NUMERIC(18,0),--TOTALXTALLADEOP
		TOTAL_OP NUMERIC(18,0),--TOTALDEOP
		TOTAL_A_MEDIR_TALLA NUMERIC(18,0)
	)
	--INSERTA LAS TALLAS DE LA OP
	INSERT INTO #TEMP(
		Empresa,
		NO_OP,
		ORDEN,
		NIVEL1,
		NIVEL2,
		NIVEL3,
		PROCESO,
		TALLA,
		CANTIDAD
	)
	SELECT
		PIT.Empresa,
		PIT.No_OP,
		PC.Orden,
		PC.Nivel1,
		PC.Nivel2,
		PC.Nivel3,
		PC.Descripcion,
		PIT.Talla,
		SUM(PIT.Cantidad)
	FROM
		OP_ASIGNACION OPA,
		OP_PROCESOS PC,
		PEDIDO_INTERNO_TALLAS PIT
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.No_OP = @NO_OP
	AND OPA.Asignada = 1
	AND OPA.Cancelada = 0
	AND	PIT.Empresa = OPA.Empresa
	AND PIT.No_OP = OPA.No_OP
	AND PIT.No_OP = PC.No_OP
	AND PC.Descripcion = 'MEDICIÓN DE PRENDAS'
	GROUP BY
		PIT.Empresa,
		PIT.No_OP,
		PC.Orden,
		PC.Nivel1,
		PC.Nivel2,
		PC.Nivel3,
		PC.Descripcion,
		PIT.Talla

	UPDATE
		#TEMP
	SET
		TOTAL_OP = (SELECT ISNULL(SUM(CANTIDAD),0) FROM #TEMP T WHERE T.Empresa = #TEMP.Empresa AND T.NO_OP = #TEMP.NO_OP AND T.ORDEN = #TEMP.ORDEN GROUP BY NO_OP,ORDEN)

	--CALCULA EL TOTAL A MEDIR DE TABLA DE MEDIDA
	UPDATE
		#TEMP
	SET
		TOTAL_A_MEDIR_TALLA = (SELECT ISNULL(CEILING((CANTIDAD/TOTAL_OP)*LAC.TamañoDeLaMuestra),0) FROM LIMITE_ACEPTABLE_CALIDAD LAC WHERE LAC.LimiteInferior <= TOTAL_OP AND LAC.LimiteSuperior >= TOTAL_OP)
	WHERE
		PROCESO IN ('MEDICIÓN DE PRENDAS')

	
	CREATE TABLE #AVANCEPROCESOS(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		CVE_PRENDA BIGINT,
		ORDEN INT,
		NIVEL1 INT,
		NIVEL2 INT,
		NIVEL3 INT,
		DESCRIPCION NVARCHAR(1000),
		CantidadOP bigint
	)

	--CREAR TABLA AUXILIAR DE FORMA DINAMICA CON LA CANTIDAD DE TALLAS QUE CONTIENE LA OP
	DECLARE @CONTADOR INT
	DECLARE @TOTALTALLAS INT
	DECLARE @TABLATEMPORALDINAMICA AS NVARCHAR(max)
	DECLARE @TALLA NVARCHAR(50)

	SELECT @TOTALTALLAS = ISNULL(COUNT(*),0) FROM #TALLASOP

	IF @TOTALTALLAS > 0
	BEGIN

		--EMPIEZA ITERACIONES PARA AGREGAR LAS COLUMNAS DE ACUERDO A LA CANTIDAD DE TALLAS CONTENDIAS EN LA OP
		--***************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'ALTER TABLE #AVANCEPROCESOS ADD '
		WHILE @CONTADOR <= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA+= 'Talla' + CONVERT(nvarchar,@CONTADOR) + ' NVARCHAR(50)'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
		END
		
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE AGREGAR COLUMNAS ***************************************************************************

		--EMPIEZA ITERACIONES PARA AGREGAR LAS TALLAS EN EL PRIMER REGISTRO DE LA TABLA #AVANCEPROCESO
		--***************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			IF @CONTADOR = 1
			BEGIN
				INSERT INTO #AVANCEPROCESOS(
					EMPRESA,
					NO_OP,
					CVE_PRENDA,
					ORDEN,
					NIVEL1,
					NIVEL2,
					NIVEL3,
					DESCRIPCION
				)
				VALUES(
					@EMPRESA,
					@NO_OP,
					-1,
					-1,
					-1,
					-1,
					-1,
					'TALLAS'
				)
			END

			SELECT @TALLA = TALLA FROM #TALLASOP WHERE CONSECUTIVO = @CONTADOR

			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR, @CONTADOR) + ' = ' + '''' +  @TALLA + ''''
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE EMPRESA = ' + CONVERT(NVARCHAR,@EMPRESA) + ' AND NO_OP = ' + CONVERT(NVARCHAR,@NO_OP) + ' AND CVE_PRENDA = -1 AND ORDEN = -1 AND NIVEL1 = -1 AND NIVEL2 = -1 AND NIVEL3 = -1'
			END
		END
		--SELECT * FROM #TALLASOP
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE INSERTAR TALLAS EN LA PRIMER REGISTRO *****************************************************
		

		--INSERTA CADA UNO DE LOS PROCESOS
		--**************************************************************************************************
		INSERT INTO #AVANCEPROCESOS(
			EMPRESA,
			NO_OP,
			CVE_PRENDA,
			ORDEN,
			NIVEL1,
			NIVEL2,
			NIVEL3,
			DESCRIPCION,
			CantidadOP
		)
		SELECT
			OPA.Empresa,
			OPA.No_OP,
			PP.Cve_Prenda,
			PP.Orden,
			PP.Nivel1,
			PP.Nivel2,
			PP.Nivel3,
			PP.Descripcion,
			SUM(PIT.Cantidad)
		FROM
			OP_ASIGNACION OPA,
			PEDIDO_INTERNO_TALLAS PIT,
			OP_PROCESOS PP
		WHERE
			OPA.Empresa = @EMPRESA
		AND OPA.No_OP = @NO_OP
		AND OPA.Asignada = 1
		AND OPA.Cancelada = 0
		AND OPA.No_OP = PIT.No_OP
		AND PIT.Empresa = OPA.Empresa
		AND PIT.No_OP = PP.No_OP
		GROUP BY
			OPA.Empresa,
			PIT.Empresa,
			PIT.No_OP,
			OPA.No_OP,
			PP.Cve_Prenda,
			PIT.Cve_Prenda,
			PP.Orden,
			PP.Nivel1,
			PP.Nivel2,
			PP.Nivel3,
			PP.Descripcion
		--FIN DE INSERTAR PROCESOS***************************************************************************


		--EMPIEZA ITERACIONES PARA ACTUALIZAR LOS AVANCES DE CADA PROCESO
		--***************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR,@CONTADOR) + '=' + 'CONVERT(NVARCHAR, (SELECT ISNULL(SUM(OPAP.Cantidad),0) FROM OP_AVANCEPROCESOS OPAP,#AVANCEPROCESOS AP WHERE OPAP.Empresa = #AVANCEPROCESOS.EMPRESA AND OPAP.No_OP = #AVANCEPROCESOS.NO_OP AND OPAP.Nivel1 = #AVANCEPROCESOS.NIVEL1 AND OPAP.Nivel2 = #AVANCEPROCESOS.NIVEL2 AND OPAP.Nivel3 = #AVANCEPROCESOS.NIVEL3 AND OPAP.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = OPAP.Empresa AND AP.NO_OP = OPAP.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))' + '+' + '''/''' + '+' + 'CONVERT(NVARCHAR,(SELECT ISNULL(SUM(PIT.Cantidad),0) FROM PEDIDO_INTERNO_TALLAS PIT,#AVANCEPROCESOS AP WHERE PIT.Empresa = #AVANCEPROCESOS.EMPRESA AND PIT.No_OP = #AVANCEPROCESOS.NO_OP AND PIT.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = PIT.Empresa AND AP.NO_OP = PIT.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION NOT IN (' + '''TALLAS''' + ',' + '''MEDICIÓN DE MOLDE''' + ',' + '''MEDICIÓN ANTES DE PROCESO''' + ',' + '''MEDICIÓN DE TABLA DE MEDIDAS''' + ',' + '''MEDICIÓN DE PRENDAS''' + ')'
			END
		END
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE ITERACIONES PARA ACTUALIZAR AVANCES DE PROCESOS*********************************************
		

		--EMPIEZA ITERACIONES PARA ACTUALIZAR LOS AVANCES DE TABLA DE MEDIDA DE MOLDE
		--***************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR,@CONTADOR) + '=' + 'CONVERT(NVARCHAR,(SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM,#AVANCEPROCESOS AP WHERE ATMM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMM.No_OP = #AVANCEPROCESOS.NO_OP AND ATMM.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND ATMM.TERMINADO = 1 AND AP.EMPRESA = ATMM.Empresa AND AP.NO_OP = ATMM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1	AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))  + ' + '''/''' + '+ CONVERT(NVARCHAR, (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM,#AVANCEPROCESOS AP WHERE ATMM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMM.No_OP = #AVANCEPROCESOS.NO_OP AND ATMM.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = ATMM.Empresa AND AP.NO_OP = ATMM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1	AND AP.NIVEL3 = -1))'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION IN (' + '''MEDICIÓN DE MOLDE''' + ')'
			END
		END
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE ITERACIONES PARA ACTUALIZAR AVANCE DE MEDIDA DE TABLA DE MOLDE*******************************

		
		--EMPIEZA ITERACIONES PARA ACTUALIZAR LOS AVANCES DE TABLA DE MEDIDA ANTES DE PROCESO
		--****************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR,@CONTADOR) + '=' + 'CONVERT(NVARCHAR,(SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP,#AVANCEPROCESOS AP WHERE ATMAP.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMAP.No_OP = #AVANCEPROCESOS.NO_OP AND ATMAP.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND ATMAP.TERMINADO = 1 AND AP.EMPRESA = ATMAP.Empresa AND AP.NO_OP = ATMAP.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1	AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))  + ' + '''/''' + '+ CONVERT(NVARCHAR, (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP,#AVANCEPROCESOS AP WHERE ATMAP.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMAP.No_OP = #AVANCEPROCESOS.NO_OP AND ATMAP.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = ATMAP.Empresa AND AP.NO_OP = ATMAP.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION IN (' + '''MEDICIÓN ANTES DE PROCESO''' + ')'
			END
		END
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE ITERACIONES PARA ACTUALIZAR AVANCE DE TABLA DE MEDIDA ANTES DE PROCESO************************


		--EMPIEZA ITERACIONES PARA ACTUALIZAR LOS AVANCES DE TABLA DE MEDIDA
		--****************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR,@CONTADOR) + '=' + 'CONVERT(NVARCHAR,(SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM,#AVANCEPROCESOS AP WHERE ATM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATM.No_OP = #AVANCEPROCESOS.NO_OP AND ATM.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND ATM.TERMINADO = 1 AND AP.EMPRESA = ATM.Empresa AND AP.NO_OP = ATM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))  + ' + '''/''' + '+ CONVERT(NVARCHAR, (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM,#AVANCEPROCESOS AP WHERE ATM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATM.No_OP = #AVANCEPROCESOS.NO_OP AND ATM.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = ATM.Empresa AND AP.NO_OP = ATM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION IN (' + '''MEDICIÓN DE TABLA DE MEDIDAS''' + ')'
			END
		END
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE ITERACIONES PARA ACTUALIZAR AVANCE DE TABLA DE MEDIDA***************************************


		--EMPIEZA ITERACIONES PARA ACTUALIZAR LOS AVANCES DE MEDICIÓN DE PRENDA
		--****************************************************************************************************
		SET @CONTADOR = 1
		SET @TABLATEMPORALDINAMICA = 'UPDATE #AVANCEPROCESOS SET '
		WHILE @CONTADOR<= @TOTALTALLAS
		BEGIN
			SET @TABLATEMPORALDINAMICA += 'TALLA' + CONVERT(NVARCHAR,@CONTADOR) + '=' + 'CONVERT(NVARCHAR, (SELECT ISNULL(SUM(OPAP.Cantidad),0) FROM OP_AVANCEPROCESOS OPAP,#AVANCEPROCESOS AP WHERE OPAP.Empresa = #AVANCEPROCESOS.EMPRESA AND OPAP.No_OP = #AVANCEPROCESOS.NO_OP AND OPAP.Nivel1 = #AVANCEPROCESOS.NIVEL1 AND OPAP.Nivel2 = #AVANCEPROCESOS.NIVEL2 AND OPAP.Nivel3 = #AVANCEPROCESOS.NIVEL3 AND OPAP.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = OPAP.Empresa AND AP.NO_OP = OPAP.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))' + '+' + '''/''' + '+' + 'CONVERT(NVARCHAR,(SELECT ISNULL(SUM(T.TOTAL_A_MEDIR_TALLA),0) FROM #TEMP T,#AVANCEPROCESOS AP WHERE T.Empresa = #AVANCEPROCESOS.EMPRESA AND T.No_OP = #AVANCEPROCESOS.NO_OP AND T.Talla = AP.TALLA' + CONVERT(NVARCHAR,@CONTADOR) + ' AND AP.EMPRESA = T.Empresa AND AP.NO_OP = T.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1))'
			SET @CONTADOR+=1
			IF @CONTADOR <= @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ','
			END
			IF @CONTADOR > @TOTALTALLAS
			BEGIN
				SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION IN (' + '''MEDICIÓN DE PRENDAS''' + ')'
			END
		END
		--SELECT @TABLATEMPORALDINAMICA
		EXEC (@TABLATEMPORALDINAMICA)
		--FIN DE ITERACIONES PARA ACTUALIZAR AVANCE DE MEDICIÓN DE PRENDA***************************************

	END


	--UPDATE
	--	#AVANCEPROCESOS
	--SET
	--	TALLA1 = CONVERT(NVARCHAR,(SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM,#AVANCEPROCESOS AP WHERE ATMM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMM.No_OP = #AVANCEPROCESOS.NO_OP AND ATMM.Talla = AP.TALLA1 AND ATMM.TERMINADO = 1 AND AP.EMPRESA = ATMM.Empresa AND AP.NO_OP = ATMM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1	AND AP.NIVEL2 = -1 AND AP.NIVEL3 = -1)) + '/' + CONVERT(NVARCHAR, (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM,#AVANCEPROCESOS AP WHERE ATMM.Empresa = #AVANCEPROCESOS.EMPRESA AND ATMM.No_OP = #AVANCEPROCESOS.NO_OP AND ATMM.Talla = AP.TALLA1 AND AP.EMPRESA = ATMM.Empresa AND AP.NO_OP = ATMM.No_OP AND AP.CVE_PRENDA = -1 AND AP.ORDEN = -1 AND AP.NIVEL1 = -1 AND AP.NIVEL2 = -1	AND AP.NIVEL3 = -1))
	--WHERE
	--	DESCRIPCION IN ('MEDICIÓN DE MOLDE')
	
	SELECT
		AP.*,
		@TOTALTALLAS AS TotalColumnasTallas
	FROM 
		#AVANCEPROCESOS AP
	
	DROP TABLE #TALLASOP
	DROP TABLE #AVANCETM_MOLDE
	DROP TABLE #AVANCETM_AP
	DROP TABLE #AVANCETM
	DROP TABLE #AVANCEPROCESOS
	DROP TABLE #TEMP

END
GO

