USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[SP_OP_VISTAAVANCE]    Script Date: 27/01/2026 06:25:13 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_OP_VISTAAVANCE]
--	DECLARE
		@EMPRESA BIGINT,
		@FINALIZADAS BIT,
		@CVE_USUCALIDADINICIAL BIGINT,
		@CVE_USUCALIDADFINAL BIGINT
AS
--	SET @EMPRESA = 1
--	SET	@FINALIZADAS = 0
--	SET @CVE_USUCALIDADINICIAL = 0
--	SET @CVE_USUCALIDADFINAL = 9999
BEGIN
	--CREACIÓN DE TABLAS AUXILIARES
	--TABLA PARA GUARDAR AVANCES DE TM_MOLDE
	CREATE TABLE #AVANCETM_MOLDE(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT,
		Fecha date,
		FechaHora Datetime
	)

	INSERT INTO #AVANCETM_MOLDE(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado,
		Fecha,
		FechaHora
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTMMTM.Talla,
		OPTMMTM.NoMedida,
		OPTMMTM.Terminado,
		CONVERT(DATE,OPTMMTM.FECHAHORA),
		OPTMMTM.FECHAHORA
	FROM
		OP_ASIGNACION OPA,
		OP_TM_MOLDE_TOMA_MEDIDA OPTMMTM
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPA.Empresa = OPTMMTM.Empresa
	AND OPA.No_OP = OPTMMTM.OP
	AND OPA.Impresa = 1
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTMMTM.Talla,
		OPTMMTM.NoMedida,
		OPTMMTM.Terminado,
		OPTMMTM.FECHAHORA
	
	--TABLA PARA GUARDAR AVANCES DE TABLA_MEDIDA ANTES DE PROCESO
	CREATE TABLE #AVANCETM_AP(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT,
		Fecha date,
		FechaHora datetime
	)

	INSERT INTO #AVANCETM_AP(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado,
		Fecha,
		FechaHora
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTMAP.Talla,
		OPTMAP.NoMedida,
		OPTMAP.Terminado,
		CONVERT(DATE,OPTMAP.FECHAHORA),
		OPTMAP.FECHAHORA
	FROM
		OP_ASIGNACION OPA,
		OP_TABLA_MEDIDAAP_TOMA_MEDIDA OPTMAP
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPA.Empresa = OPTMAP.Empresa
	AND OPA.No_OP = OPTMAP.OP
	AND OPA.Impresa = 1
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTMAP.Talla,
		OPTMAP.NoMedida,
		OPTMAP.Terminado,
		OPTMAP.FECHAHORA


	--TABLA PARA GUARDAR AVANCES DE TABLA_MEDIDA
	CREATE TABLE #AVANCETM(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT,
		Fecha date,
		FechaHora datetime
	)

	INSERT INTO #AVANCETM(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado,
		Fecha,
		FechaHora
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado,
		CONVERT(DATE,OPTM.FECHAHORA),
		OPTM.FECHAHORA
	FROM
		OP_ASIGNACION OPA,
		OP_TABLA_MEDIDA_TOMA_MEDIDA OPTM
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPTM.Empresa = OPA.Empresa
	AND OPA.No_OP = OPTM.OP
	AND OPA.Impresa = 1
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado,
		OPTM.FECHAHORA

	--TABLA CANTIDAD DE MUETRAS A MEDIR CUANDO NO HAY TABLA DE MEDIDA
	CREATE TABLE #TEMP
	(
		Empresa bigint,
		NO_OP NUMERIC(18,0),
		ORDEN INT,
		NIVEL1 INT,
		NIVEL2 INT,
		NIVEL3 INT,
		PROCESO NVARCHAR(150),
		TALLA NVARCHAR(20), 
		CANTIDAD NUMERIC(18,0),--TOTALXTALLADEOP
		TOTAL_OP NUMERIC(18,0),--TOTALDEOP
		TOTAL_A_MEDIR_TALLA NUMERIC(18,0)
	)
	--INSERTA LAS TALLAS DE LA OP
	INSERT INTO #TEMP(
		Empresa,
		NO_OP,
		ORDEN,
		NIVEL1,
		NIVEL2,
		NIVEL3,
		PROCESO,
		TALLA,
		CANTIDAD
	)
	SELECT
		PIT.Empresa,
		PIT.No_OP,
		PC.Orden,
		PC.Nivel1,
		PC.Nivel2,
		PC.Nivel3,
		PC.Descripcion,
		PIT.Talla,
		SUM(PIT.Cantidad-ISNULL(RIPT.CANTIDAD,0))
	FROM
		OP_ASIGNACION OPA,
		OP_PROCESOS PC,
		PEDIDO_INTERNO_TALLAS PIT
		LEFT JOIN
			RESERVADO_INVENTARIO_PRODUCTO_TERMINADO RIPT
		ON
			RIPT.Empresa = PIT.Empresa
		AND RIPT.No_Pedido = PIT.No_Pedido
		AND RIPT.Partida = PIT.Partida
		AND RIPT.Cve_Prenda = PIT.Cve_Prenda
		AND RIPT.LugarDeEntrega = PIT.LugarDeEntrega
		AND RIPT.Prioridad = PIT.Prioridad
		AND RIPT.Talla = PIT.Talla
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND	PIT.Empresa = OPA.Empresa
	AND PIT.No_OP = OPA.No_OP
	AND PIT.No_OP = PC.No_OP
	AND PC.Descripcion = 'MEDICIÓN DE PRENDAS'
	AND OPA.Impresa = 1
	GROUP BY
		PIT.Empresa,
		PIT.No_OP,
		PC.Orden,
		PC.Nivel1,
		PC.Nivel2,
		PC.Nivel3,
		PC.Descripcion,
		PIT.Talla

	UPDATE
		#TEMP
	SET
		TOTAL_OP = (SELECT ISNULL(SUM(CANTIDAD),0) FROM #TEMP T WHERE T.Empresa = #TEMP.Empresa AND T.NO_OP = #TEMP.NO_OP AND T.ORDEN = #TEMP.ORDEN GROUP BY NO_OP,ORDEN)

	--CALCULA EL TOTAL A MEDIR DE TABLA DE MEDIDA
	UPDATE
		#TEMP
	SET
		TOTAL_A_MEDIR_TALLA = (SELECT ISNULL(CEILING((CANTIDAD/TOTAL_OP)*LAC.TamañoDeLaMuestra),0) FROM LIMITE_ACEPTABLE_CALIDAD LAC WHERE LAC.LimiteInferior <= TOTAL_OP AND LAC.LimiteSuperior >= TOTAL_OP)
	WHERE
		PROCESO IN ('MEDICIÓN DE PRENDAS')


	--TABLA PARA GUARDAR AVANCES DE PROCESOS
	CREATE TABLE #AVANCEPROCESOS(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		NIVEL1 INT,
		NIVEL2 INT,
		NIVEL3 INT,
		CANTIDADAVANCE BIGINT,
		Fecha DATE,
		FechaHora datetime
	)
	INSERT INTO #AVANCEPROCESOS(
		EMPRESA,
		NO_OP,
		NIVEL1,
		NIVEL2,
		NIVEL3,
		CANTIDADAVANCE,
		Fecha,
		FechaHora
	)
	SELECT
		OPAP.Empresa,
		OPAP.No_OP,
		OPAP.Nivel1,
		OPAP.Nivel2,
		OPAP.Nivel3,
		SUM(OPAP.CANTIDAD),
		CONVERT(DATE,OPAP.Fecha),
		OPAP.Fecha
	FROM
		OP_AVANCEPROCESOS OPAP,
		OP_ASIGNACION OPA
	WHERE 
		OPAP.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPA.Empresa = OPAP.Empresa
	AND OPA.No_OP = OPAP.No_OP
	AND OPA.Impresa = 1
	GROUP BY 
		OPAP.Empresa,
		OPAP.No_OP,
		OPAP.Nivel1,
		OPAP.Nivel2,
		OPAP.Nivel3,
		OPAP.Fecha

	--TABLA PROCESOS
	CREATE TABLE #PROCESOSOP(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		CVE_PRENDA BIGINT,
		ORDEN INT,
		NIVEL1 INT,
		NIVEL2 INT,
		NIVEL3 INT,
		DESCRIPCION NVARCHAR(1000),
		CantidadTotalProcesos bigint,
		CantidadOP bigint,
		PorcentajeTotalPorProceso numeric(28,10),
		CantidadAvance BIGINT,
		CantidadAvanceMenosUnDia BIGINT,
		CantidadAvanceMenosUnaSemana BIGINT,
		PorcentajeAvancePorProceso numeric(28,10),
		PorcentajeAvancePorProcesoMenosUnDia numeric(28,10),
		PorcentajeAvancePorProcesoMenosUnaSemana numeric(28,10)
	)

	INSERT INTO #PROCESOSOP(
		EMPRESA,
		NO_OP,
		CVE_PRENDA,
		ORDEN,
		NIVEL1,
		NIVEL2,
		NIVEL3,
		DESCRIPCION,
		CantidadTotalProcesos,
		CantidadOP,
		CantidadAvance,
		CantidadAvanceMenosUnDia,
		CantidadAvanceMenosUnaSemana
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		PP.Cve_Prenda,
		PP.Orden,
		PP.Nivel1,
		PP.Nivel2,
		PP.Nivel3,
		PP.Descripcion,
		(SELECT ISNULL(COUNT(*),0) FROM OP_PROCESOS PP1 WHERE PP1.No_OP = OPA.No_OP) AS CantidadTotalProcesos,
		CASE PP.Descripcion
			WHEN 'MEDICIÓN DE MOLDE' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM WHERE ATMM.Empresa = OPA.EMPRESA AND ATMM.NO_OP = OPA.No_OP)
			WHEN 'MEDICIÓN ANTES DE PROCESO' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP WHERE ATMAP.Empresa = OPA.EMPRESA AND ATMAP.NO_OP = OPA.No_OP)
			WHEN 'MEDICIÓN DE TABLA DE MEDIDAS' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM WHERE ATM.Empresa = OPA.EMPRESA AND ATM.NO_OP = OPA.No_OP)
			WHEN 'MEDICIÓN DE PRENDAS' THEN (SELECT ISNULL(SUM(T.TOTAL_A_MEDIR_TALLA),0) FROM #TEMP T WHERE T.Empresa = OPA.EMPRESA AND T.NO_OP = OPA.No_OP)
		ELSE
			(SELECT ISNULL(SUM(PIT1.Cantidad-ISNULL(RIPT.CANTIDAD,0)),0) FROM PEDIDO_INTERNO_TALLAS PIT1 LEFT JOIN RESERVADO_INVENTARIO_PRODUCTO_TERMINADO RIPT ON RIPT.Empresa = PIT1.Empresa AND RIPT.No_Pedido = PIT1.No_Pedido AND RIPT.Partida = PIT1.Partida AND RIPT.Cve_Prenda = PIT1.Cve_Prenda	AND RIPT.LugarDeEntrega = PIT1.LugarDeEntrega AND RIPT.Prioridad = PIT1.Prioridad AND RIPT.Talla = PIT1.Talla WHERE PIT1.Empresa = PIT.Empresa AND PIT1.No_OP = PIT.No_OP)
		END AS CantidadOP,
		CASE PP.Descripcion
			WHEN 'MEDICIÓN DE MOLDE' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM WHERE ATMM.Empresa = OPA.EMPRESA AND ATMM.NO_OP = OPA.No_OP AND ATMM.Terminado = 1)
			WHEN 'MEDICIÓN ANTES DE PROCESO' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP WHERE ATMAP.Empresa = OPA.EMPRESA AND ATMAP.NO_OP = OPA.No_OP AND ATMAP.Terminado = 1)
			WHEN 'MEDICIÓN DE TABLA DE MEDIDAS' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM WHERE ATM.Empresa = OPA.EMPRESA AND ATM.NO_OP = OPA.No_OP AND ATM.Terminado = 1)
		ELSE
			(SELECT ISNULL(SUM(AP.CANTIDADAVANCE),0) FROM #AVANCEPROCESOS AP WHERE AP.Empresa = PIT.Empresa AND AP.No_OP = PIT.No_OP AND PIT.Cve_Prenda = PP.Cve_Prenda AND AP.NIVEL1 = PP.Nivel1 AND AP.NIVEL2 = PP.Nivel2 AND AP.NIVEL3 = PP.Nivel3)
		END AS CantidadAvance,
		CASE PP.Descripcion
			WHEN 'MEDICIÓN DE MOLDE' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM WHERE ATMM.Empresa = OPA.EMPRESA AND ATMM.NO_OP = OPA.No_OP AND ATMM.Terminado = 1 AND ATMM.FechaHora <= DATEADD(hour, 8, DATEADD(DAY, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
			WHEN 'MEDICIÓN ANTES DE PROCESO' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP WHERE ATMAP.Empresa = OPA.EMPRESA AND ATMAP.NO_OP = OPA.No_OP AND ATMAP.Terminado = 1 AND ATMAP.FechaHora <= DATEADD(hour, 8, DATEADD(DAY, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
			WHEN 'MEDICIÓN DE TABLA DE MEDIDAS' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM WHERE ATM.Empresa = OPA.EMPRESA AND ATM.NO_OP = OPA.No_OP AND ATM.Terminado = 1 AND ATM.FechaHora <= DATEADD(hour, 8, DATEADD(DAY, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
		ELSE
			(SELECT ISNULL(SUM(AP.CANTIDADAVANCE),0) FROM #AVANCEPROCESOS AP WHERE AP.Empresa = PIT.Empresa AND AP.No_OP = PIT.No_OP AND PIT.Cve_Prenda = PP.Cve_Prenda AND AP.NIVEL1 = PP.Nivel1 AND AP.NIVEL2 = PP.Nivel2 AND AP.NIVEL3 = PP.Nivel3 AND AP.FechaHora <= DATEADD(hour, 8, DATEADD(DAY, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
		END AS CantidadAvanceMenosUnDia,
		CASE PP.Descripcion
			WHEN 'MEDICIÓN DE MOLDE' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_MOLDE ATMM WHERE ATMM.Empresa = OPA.EMPRESA AND ATMM.NO_OP = OPA.No_OP AND ATMM.Terminado = 1 AND ATMM.FechaHora <= DATEADD(hour, 8, DATEADD(WEEK, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
			WHEN 'MEDICIÓN ANTES DE PROCESO' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM_AP ATMAP WHERE ATMAP.Empresa = OPA.EMPRESA AND ATMAP.NO_OP = OPA.No_OP AND ATMAP.Terminado = 1 AND ATMAP.FechaHora <= DATEADD(hour, 8, DATEADD(WEEK, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
			WHEN 'MEDICIÓN DE TABLA DE MEDIDAS' THEN (SELECT ISNULL(COUNT(*),0) FROM #AVANCETM ATM WHERE ATM.Empresa = OPA.EMPRESA AND ATM.NO_OP = OPA.No_OP AND ATM.Terminado = 1 AND ATM.FechaHora <= DATEADD(hour, 8, DATEADD(WEEK, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
		ELSE
			(SELECT ISNULL(SUM(AP.CANTIDADAVANCE),0) FROM #AVANCEPROCESOS AP WHERE AP.Empresa = PIT.Empresa AND AP.No_OP = PIT.No_OP AND PIT.Cve_Prenda = PP.Cve_Prenda AND AP.NIVEL1 = PP.Nivel1 AND AP.NIVEL2 = PP.Nivel2 AND AP.NIVEL3 = PP.Nivel3 AND AP.FechaHora <= DATEADD(hour, 8, DATEADD(WEEK, -1, CONVERT(DATETIME, CONVERT(DATE, GETDATE())))))
		END AS CantidadAvanceMenosUnaSemana
	FROM
		OP_ASIGNACION OPA,
		OP_PROCESOS PP,
		MAQUILADOR M,
		PEDIDO_INTERNO_TALLAS PIT
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPA.No_OP = PIT.No_OP
	AND PIT.Empresa = OPA.Empresa
	AND PIT.No_OP = PP.No_OP
	AND M.Cve_Maquilador = OPA.Cve_Maquilador
	AND M.Cve_UsuCalidad >= @CVE_USUCALIDADINICIAL
	AND M.Cve_UsuCalidad <= @CVE_USUCALIDADFINAL
	AND OPA.Impresa = 1
	GROUP BY
		OPA.Empresa,
		PIT.Empresa,
		PIT.No_OP,
		OPA.No_OP,
		PP.Cve_Prenda,
		PIT.Cve_Prenda,
		PP.Orden,
		PP.Nivel1,
		PP.Nivel2,
		PP.Nivel3,
		PP.Descripcion

	--SE ACTUALIZA LA COLUMNA DE PORCENTAJE TOTAL POR PROCESO Y PORCENTAJE DE AVANCE POR PROCESO
	UPDATE
		#PROCESOSOP
	SET
		PorcentajeTotalPorProceso = (1/CONVERT(NUMERIC(28,10),CantidadTotalProcesos))*100,
		PorcentajeAvancePorProceso = (CantidadAvance*((1/CONVERT(NUMERIC(28,10),CantidadTotalProcesos))*100))/CantidadOP,
		PorcentajeAvancePorProcesoMenosUnDia = (CantidadAvanceMenosUnDia*((1/CONVERT(NUMERIC(28,10),CantidadTotalProcesos))*100))/CantidadOP,
		PorcentajeAvancePorProcesoMenosUnaSemana = (CantidadAvanceMenosUnaSemana*((1/CONVERT(NUMERIC(28,10),CantidadTotalProcesos))*100))/CantidadOP

	DROP TABLE #AVANCETM_MOLDE
	DROP TABLE #AVANCETM_AP
	DROP TABLE #AVANCETM
	DROP TABLE #AVANCEPROCESOS
	DROP TABLE #TEMP

	SELECT
		OPA.Cve_Maquilador,
		M.Encargado,
		OPA.No_OP,
		OPA.No_OPSistemaAnterior,
		P.Cve_Prenda,
		PIT.DescripcionPrenda,
		OPA.FechaInicio AS FechaCreacion,
		OPA.FechaFinalizacion AS FechaVencimiento,
		PI.Cve_Cliente,
		PI.Nom_Cliente,
		SUM(PIT.Cantidad-ISNULL(RIPT.CANTIDAD,0)) AS CANT_OP,
		(SELECT ISNULL(COUNT(*),0) FROM OP_EXPLOSION_MATERIALES OPEM WHERE OPEM.Empresa = OPA.Empresa AND OPEM.No_OP = OPA.No_OP AND OPEM.RecibidoCompletoPorMaquilador = 0 and OPEM.NoSeRequirio = 0) AS FaltaRecibir,
		(SELECT MAX(FechaFirmaAcuse) FROM OP_ACUSES_RECIBOMATERIAL OPEMI WHERE OPEMI.Empresa = OPA.Empresa AND OPEMI.No_OP = OPA.No_OP) AS FechaConfirmacionMateriales,
		(SELECT ISNULL(COUNT(*),0) FROM OP_EXPLOSION_MATERIALES OPEM WHERE OPEM.Empresa = OPA.Empresa AND OPEM.No_OP = OPA.No_OP AND OPEM.InspeccionadoCompletoPorInspector = 0 and OPEM.NoSeRequirio = 0) AS FaltaInspeccionar,
		(SELECT MAX(FechaMovimiento) FROM OP_EXPLOSION_MATERIALES_INSPECTOR OPEMI WHERE OPEMI.Empresa = OPA.Empresa AND OPEMI.No_OP = OPA.No_OP AND OPEMI.TipoMovimiento = 'RECIBIDO') AS FechaInspeccionMateriales,
		CONVERT(NUMERIC(18,2),(SELECT SUM(POP.PorcentajeAvancePorProceso) FROM #PROCESOSOP POP WHERE POP.EMPRESA = OPA.Empresa AND POP.NO_OP = OPA.No_OP)) AS PorcentajeAvanceOP,
		CONVERT(NUMERIC(18,2),(SELECT SUM(POP.PorcentajeAvancePorProcesoMenosUnDia) FROM #PROCESOSOP POP WHERE POP.EMPRESA = OPA.Empresa AND POP.NO_OP = OPA.No_OP)) AS PorcentajeAvanceOPMenosUnDia,
		CONVERT(NUMERIC(18,2),(SELECT SUM(POP.PorcentajeAvancePorProcesoMenosUnaSemana) FROM #PROCESOSOP POP WHERE POP.EMPRESA = OPA.Empresa AND POP.NO_OP = OPA.No_OP)) AS PorcentajeAvanceOPMenosUnaSemana,
		--STUFF((SELECT 'vbCrLf' + 'vbCrLf + convert(nvarchar(2),day(OPPO.FECHAHORA)) + '/' + RIGHT('00'+ CAST(month(OPPO.FECHAHORA) AS VARCHAR),2) + '/' + convert(nvarchar(4),year(OPPO.FECHAHORA))  + ': ' + CONVERT(NVARCHAR(MAX),OPPO.Observacion) FROM OP_PROCESOS_OBSERVACIONES OPPO WHERE OPPO.Empresa = OPA.Empresa AND OPPO.No_OP = OPA.No_OP FOR XML PATH('')), 1, 2, '') AS OBSERVACIONES
		STUFF((SELECT CHAR(13) + CHAR(10) + RIGHT('00'+ CAST(day(OPPO.FECHAHORA) AS VARCHAR),2) + '/' + RIGHT('00'+ CAST(month(OPPO.FECHAHORA) AS VARCHAR),2) + '/' + RIGHT('0000'+ CAST(year(OPPO.FECHAHORA) AS VARCHAR),4)  + ': ' + CONVERT(NVARCHAR(MAX),OPPO.Observacion) FROM OP_PROCESOS_OBSERVACIONES OPPO WHERE OPPO.Empresa = OPA.Empresa AND OPPO.No_OP = OPA.No_OP FOR XML PATH(''),TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS OBSERVACIONES
	FROM
		PEDIDO_INTERNO PI,
		PRENDA P,
		MAQUILADOR M,
		OP_ASIGNACION OPA,
		PEDIDO_INTERNO_TALLAS PIT
		LEFT JOIN
			RESERVADO_INVENTARIO_PRODUCTO_TERMINADO RIPT
		ON
			RIPT.Empresa = PIT.Empresa
		AND RIPT.No_Pedido = PIT.No_Pedido
		AND RIPT.Partida = PIT.Partida
		AND RIPT.Cve_Prenda = PIT.Cve_Prenda
		AND RIPT.LugarDeEntrega = PIT.LugarDeEntrega
		AND RIPT.Prioridad = PIT.Prioridad
		AND RIPT.Talla = PIT.Talla
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.Asignada = 1
	AND OPA.Cancelada = 0
	AND OPA.Finalizada = @FINALIZADAS
	AND OPA.Cancelada = 0
	AND OPA.Cve_Maquilador = M.Cve_Maquilador
	AND PI.Empresa = PIT.Empresa
	AND PI.No_Pedido = PIT.No_Pedido
	AND OPA.No_OP = PIT.No_OP
	AND PIT.Cve_Prenda = P.Cve_Prenda
	AND M.Cve_UsuCalidad >= @CVE_USUCALIDADINICIAL
	AND M.Cve_UsuCalidad <= @CVE_USUCALIDADFINAL
	AND OPA.Impresa = 1
	GROUP BY
		OPA.Empresa,
		OPA.Cve_Maquilador,
		M.Encargado,
		OPA.No_OP,
		OPA.No_OPSistemaAnterior,
		P.Cve_Prenda,
		PIT.DescripcionPrenda,
		OPA.FechaInicio,
		OPA.FechaFinalizacion,
		PI.Cve_Cliente,
		PI.Nom_Cliente
	ORDER BY
		M.Encargado,
		OPA.No_OP

	DROP TABLE #PROCESOSOP
END

--select * from OP_ASIGNACION
--select No_OP from OP_EXPLOSION_MATERIALES GROUP BY No_OP ORDER BY No_OP
--select * from OP_EXPLOSION_MATERIALES
--select * from OP_EXPLOSION_MATERIALES_INSPECTOR
--exec SP_OP_VISTAAVANCE 1,0,0,9999

--SELECT * FROM OP_PROCESOS_OBSERVACIONES WHERE EMPRESA = 1 AND No_OP = 94 ORDER BY FECHAHORA ASC
--SELECT No_OP FROM PEDIDO_INTERNO_TALLAS WHERE No_Pedido = 1200 GROUP BY No_OP
GO

