USE [NORCELEC]
GO

/****** Object:  StoredProcedure [dbo].[SP_OP_CONSULTA_AVANCE_TABLA_MEDIDA_TOMA_MEDIDA]    Script Date: 04/07/2025 01:40:51 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_OP_CONSULTA_AVANCE_TABLA_MEDIDA_TOMA_MEDIDA]
--	DECLARE
		@EMPRESA AS BIGINT,
		@NO_OP AS BIGINT
AS
BEGIN
--	SET @EMPRESA = 1
--	SET	@NO_OP = 3

	DECLARE @CVE_PRENDA AS BIGINT
	
	SELECT TOP 1
		@CVE_PRENDA = Cve_Prenda
	FROM
		PEDIDO_INTERNO_TALLAS PIT
	WHERE
		PIT.Empresa = @EMPRESA
	AND PIT.No_OP = @NO_OP

	--TABLA PARA GUARDAR AVANCES DE TABLA_MEDIDA
	CREATE TABLE #AVANCETM(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		NoMedida INT,
		Terminado BIT
	)

	INSERT INTO #AVANCETM(
		EMPRESA,
		NO_OP,
		TALLA,
		NoMedida,
		Terminado
	)
	SELECT
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado
	FROM
		OP_ASIGNACION OPA,
		OP_TABLA_MEDIDA_TOMA_MEDIDA OPTM
	WHERE
		OPA.Empresa = @EMPRESA
	AND OPA.No_OP = @NO_OP
	AND OPA.Empresa = OPTM.Empresa
	AND OPA.No_OP = OPTM.OP
	GROUP BY 
		OPA.Empresa,
		OPA.No_OP,
		OPTM.Talla,
		OPTM.NoMedida,
		OPTM.Terminado

	--TABLA PARA OBTENER LA CANTIDAD DE TALLAS DE LA OP
	CREATE TABLE #TALLASOP(
		EMPRESA BIGINT,
		CONSECUTIVO INT IDENTITY(1,1),
		PARTIDA INT,
		TALLA NVARCHAR(25),
		CANTIDAD BIGINT
	)
	INSERT INTO #TALLASOP(
		EMPRESA,
		PARTIDA,
		TALLA,
		CANTIDAD
	)
	SELECT 
		PIT.Empresa,
		PEM.Partida,
		PEM.Talla,
		SUM(PIT.Cantidad) AS Cantidad
	FROM 
		PEDIDO_INTERNO_TALLAS PIT,
		PRENDA_ESTRUCTURA_MATERIALES PEM
	WHERE
		PIT.Empresa = @EMPRESA
	AND PIT.No_OP = @NO_OP
	AND PEM.Cve_Prenda = PIT.Cve_Prenda
	AND PEM.Talla = PIT.Talla
	GROUP BY
		PIT.Empresa,
		PEM.Partida,
		PEM.Talla
	ORDER BY
		PEM.Partida

	--TABLA PARA GUARDAR LA CANTIDAD MÁXIMA DE MEDIDAS QUE SE VAN A HACER POR CADA TALLA
	CREATE TABLE #CANTIDADMEDICIONES(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		TALLA NVARCHAR(20),
		CantidadMedidas INT
	)
	INSERT INTO #CANTIDADMEDICIONES(
		EMPRESA,
		NO_OP,
		TALLA,
		CantidadMedidas
	)
	SELECT
		EMPRESA,
		NO_OP,
		TALLA,
		COUNT(*)
	FROM
		#AVANCETM
	GROUP BY
		EMPRESA,
		NO_OP,
		TALLA

	DECLARE @MAXCANTIDADMEDICIONES AS INT
	--SE OBTIENE EL MAYOR DE MEDIDAS PARA CREAR LAS COLUMNAS DE FORMA DINAMICA
	SELECT
		@MAXCANTIDADMEDICIONES = MAX(CantidadMedidas)
	FROM
		#CANTIDADMEDICIONES
	
	--SE CREA TABLA DONDE SE GUARDARAN LOS DATOS
	CREATE TABLE #TOMA_MEDIDA(
		EMPRESA BIGINT,
		NO_OP BIGINT,
		CVE_PRENDA BIGINT,
		MAXCANTIDADMEDIDAS INT,
		PARTIDA INT,
		DESCRIPCION_MEDIDA NVARCHAR(255),
		TALLA NVARCHAR(50),
		TOLERANCIA NUMERIC(18,4),
		ESPECIFICACION NUMERIC(18,4)
	)

	DECLARE @CONTADOR INT
	DECLARE @TOTALTALLAS INT
	DECLARE @TOTALMEDIDAS INT
	DECLARE @TABLATEMPORALDINAMICA AS NVARCHAR(max)
	DECLARE @TALLA NVARCHAR(50)

	--SE AGREGAN COLUMNAS NECESARIAS
	--EMPIEZA ITERACIONES PARA AGREGAR LAS COLUMNAS DE ACUERDO A LA CANTIDAD DE TALLAS CONTENDIAS EN LA OP
	--***************************************************************************************************
	SET @CONTADOR = 1
	SET @TABLATEMPORALDINAMICA = 'ALTER TABLE #TOMA_MEDIDA ADD '
	WHILE @CONTADOR <= @MAXCANTIDADMEDICIONES
	BEGIN
		SET @TABLATEMPORALDINAMICA+= 'TomaMedida' + CONVERT(nvarchar,@CONTADOR) + ' NUMERIC(18,4), TerminadoTomaMedida' + CONVERT(nvarchar,@CONTADOR) + ' BIT'
		SET @CONTADOR+=1
		IF @CONTADOR <= @MAXCANTIDADMEDICIONES
		BEGIN
			SET @TABLATEMPORALDINAMICA+= ','
		END
	END
		
	--SELECT @TABLATEMPORALDINAMICA
	EXEC (@TABLATEMPORALDINAMICA)
	--FIN DE AGREGAR COLUMNAS ***************************************************************************

	---INSERTA LAS MEDIDAS Y ESPECIFICACIONES POR TALLA PARA LLENAR LAS COLUMNAS POSTERIORMENTE CON LAS MEDIDAS TOMADAS
	INSERT INTO #TOMA_MEDIDA(
		EMPRESA,
		NO_OP,
		CVE_PRENDA,
		MAXCANTIDADMEDIDAS,
		PARTIDA,
		DESCRIPCION_MEDIDA,
		TALLA,
		TOLERANCIA,
		ESPECIFICACION
	)
	SELECT 
		@EMPRESA,
		@NO_OP,
		PTM.Cve_Prenda,
		@MAXCANTIDADMEDICIONES,
		PTMD.Partida,
		PTM.Descripcion_Medida,
		PTMD.Talla,
		PTM.Tolerancia,
		PTMD.Especificacion
	FROM 
		PRENDA_TABLA_MEDIDA PTM,
		PRENDA_TABLA_MEDIDA_DETALLE PTMD,
		#TALLASOP TAOP
	WHERE 
		PTM.Cve_Prenda = @CVE_PRENDA
	AND PTMD.Cve_Prenda = PTM.Cve_Prenda
	AND PTMD.Partida = PTM.Partida
	AND TAOP.TALLA = PTMD.Talla

	SELECT @TOTALTALLAS = ISNULL(COUNT(*),0) FROM #TALLASOP

	--CREA TABLA RESUMEN DE TOMA DE MEDIDAS PARA CONVERTIRLA EN COLUMNAS EN LA TABLA PRINCIPAL
	CREATE TABLE #RESUMEN_TOMA_MEDIDA(
		CVE_PRENDA BIGINT,
		PARTIDA INT,
		TALLA NVARCHAR(50),
		No_Medida int,
		Toma_Medida NUMERIC(18,4),
		Terminado BIT
	)
	INSERT INTO #RESUMEN_TOMA_MEDIDA(
		CVE_PRENDA,
		PARTIDA,
		TALLA,
		No_Medida,
		Toma_Medida,
		Terminado
	)
	SELECT 
		PTM.Cve_Prenda,
		PTMD.Partida,
		PTMD.Talla,
		OPTMTM.NoMedida,
		ISNULL(OPTMTM.Toma_Medida,0) AS Toma_Medida,
		OPTMTM.Terminado
	FROM 
		PRENDA_TABLA_MEDIDA PTM,
		PRENDA_TABLA_MEDIDA_DETALLE PTMD,
		OP_TABLA_MEDIDA_TOMA_MEDIDA OPTMTM
	WHERE 
		PTM.Cve_Prenda = @CVE_PRENDA
	AND PTMD.Cve_Prenda = PTM.Cve_Prenda
	AND PTMD.Partida = PTM.Partida
	AND OPTMTM.Empresa = @EMPRESA
	AND OPTMTM.OP = @NO_OP
	AND OPTMTM.Partida = PTM.Partida
	AND OPTMTM.Talla = PTMD.Talla
	ORDER BY
		PTMD.Talla,
		OPTMTM.NoMedida,
		PTMD.Partida


	--EMPIEZA ITERACIONES PARA ACTUALIZAR LAS MEDIDAS TOMADAS
	--***************************************************************************************************
	SET @CONTADOR = 1
	--SET @TABLATEMPORALDINAMICA = 'UPDATE #TOMA_MEDIDA SET '
	WHILE @CONTADOR<= @MAXCANTIDADMEDICIONES
	BEGIN
		SET @TABLATEMPORALDINAMICA = 'UPDATE #TOMA_MEDIDA SET TomaMedida' + CONVERT(NVARCHAR,@CONTADOR) + '=RTM.Toma_Medida,TerminadoTomaMedida' + CONVERT(NVARCHAR,@CONTADOR) + '=RTM.Terminado FROM #TOMA_MEDIDA TM,#RESUMEN_TOMA_MEDIDA RTM WHERE TM.TALLA = RTM.TALLA AND TM.PARTIDA = RTM.PARTIDA AND RTM.No_Medida = ' + CONVERT(NVARCHAR,@CONTADOR)
		SET @CONTADOR+=1
		--IF @CONTADOR <= @TOTALTALLAS
		--BEGIN
		--	SET @TABLATEMPORALDINAMICA+= ','
		--END
		--IF @CONTADOR > @TOTALTALLAS
		--BEGIN
		--	SET @TABLATEMPORALDINAMICA+= ' WHERE DESCRIPCION NOT IN (' + '''TALLAS''' + ',' + '''MEDICIÓN DE MOLDE''' + ',' + '''MEDICIÓN ANTES DE PROCESO''' + ',' + '''MEDICIÓN DE TABLA DE MEDIDAS''' + ')'
		--END
		EXEC (@TABLATEMPORALDINAMICA)
	END
	--SELECT @TABLATEMPORALDINAMICA
	--FIN DE ITERACIONES PARA ACTUALIZAR TOMAS DE MEDIDAS************************************************

	SELECT * FROM #TOMA_MEDIDA

	DROP TABLE #AVANCETM
	DROP TABLE #CANTIDADMEDICIONES
	DROP TABLE #TOMA_MEDIDA
	DROP TABLE #TALLASOP
	DROP TABLE #RESUMEN_TOMA_MEDIDA
	
END
GO

