USE [NORCELEC]
GO

/****** Object:  Table [dbo].[HABILITACION_GRUPO]    Script Date: 09/10/2025 11:31:31 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HABILITACION_GRUPO](
	[Cve_Grupo] [nvarchar](3) NOT NULL,
	[Descripcion] [nvarchar](50) NULL,
	[Unidad] [nvarchar](50) NULL,
	[Status] [bit] NULL,
	[USUARIO] [numeric](18, 0) NULL,
	[FECHAHORA] [datetime] NULL,
	[COMPUTADORA] [nvarchar](50) NULL,
 CONSTRAINT [PK_HABILITACIONES_GRUPO] PRIMARY KEY CLUSTERED 
(
	[Cve_Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

