USE [NORCELEC]
GO

/****** Object:  Table [dbo].[PRENDA_INVENTARIO]    Script Date: 07/08/2025 07:01:42 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRENDA_INVENTARIO](
	[Empresa] [bigint] NOT NULL,
	[Cve_Prenda] [bigint] NOT NULL,
	[Talla] [nvarchar](50) NOT NULL,
	[Cantidad] [bigint] NULL,
 CONSTRAINT [PK_PRENDA_INVENTARIO] PRIMARY KEY CLUSTERED 
(
	[Empresa] ASC,
	[Cve_Prenda] ASC,
	[Talla] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

