USE [NORCELEC]
GO

/****** Object:  Table [dbo].[PRENDA_ESTRUCTURA_MATERIALES]    Script Date: 20/01/2026 01:34:42 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRENDA_ESTRUCTURA_MATERIALES](
	[Cve_Prenda] [numeric](18, 0) NOT NULL,
	[Partida] [bigint] NOT NULL,
	[Talla] [nvarchar](50) NULL,
	[USUARIO] [numeric](18, 0) NULL,
	[FECHA_HORA] [datetime] NULL,
	[COMPUTADORA] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRENDA_ESTRUCTURA_MATERIALES] PRIMARY KEY CLUSTERED 
(
	[Cve_Prenda] ASC,
	[Partida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

