USE [NORCELEC]
GO

/****** Object:  Table [dbo].[TALLAS_GENERALES]    Script Date: 07/07/2025 12:02:01 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TALLAS_GENERALES](
	[Partida] [bigint] NOT NULL,
	[Talla] [nvarchar](50) NULL,
 CONSTRAINT [PK_TALLAS_GENERALES] PRIMARY KEY CLUSTERED 
(
	[Partida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

