USE [NORCELEC]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 10/07/2025 06:45:30 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[CVE_USU] [numeric](18, 0) NOT NULL,
	[NOM_USUARIO] [nvarchar](50) NULL,
	[PUESTO] [nvarchar](50) NULL,
	[DEPARTAMENTO] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[CONTRASEÑA] [nvarchar](8) NULL,
	[ProgramaRutaTrabajo] [bit] NULL,
	[STATUS] [bit] NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[CVE_USU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

